function letter_get_e_planet() {
	// letter_get_e();
	//e = 0 vowel e = 1 const

	if e = 1 get_type = 0;
	if e = 0 get_type = 1;
	var fix;

	if get_type = 0{
	t_sec = round(random_range(0,4)); sec = 0;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	if has_m = false{
	    fix[__t] = "heim"; __t += 1;
	    fix[__t] = "shire"; __t += 1;
	    fix[__t] = "garde"; __t += 1;
	    fix[__t] = "grad"; __t += 1;
	    fix[__t] = "mar"; __t += 1;
	    fix[__t] = "dor"; __t += 1;
	    fix[__t] = "land"; __t += 1;
	    fix[__t] = "lora"; __t += 1;
	    fix[__t] = "hil"; __t += 1; 
	    fix[__t] = "hen"; __t += 1;
	    fix[__t] = "dale"; __t += 1;
	    fix[__t] = "vale"; __t += 1;
	    fix[__t] = "na"; __t += 1;  
	    fix[__t] = "mark"; __t += 1;
	    fix[__t] = "boro"; __t += 1;
	    fix[__t] = "lorn"; __t += 1;}
    
	    fix[__t] = "a"; __t += 1;
	    fix[__t] = "anta"; __t += 1;
	    fix[__t] = "ania"; __t += 1;
	    fix[__t] = "aria"; __t += 1;
	    fix[__t] = "aan"; __t += 1;
	    fix[__t] = "aar"; __t += 1;
	    fix[__t] = "ades"; __t += 1;
	    fix[__t] = "aas"; __t += 1;
	    fix[__t] = "ac"; __t += 1;
	    fix[__t] = "aus"; __t += 1;
	    fix[__t] = "aeva"; __t += 1;
	    fix[__t] = "ach"; __t += 1;
	    fix[__t] = "aca"; __t += 1;
	    fix[__t] = "ae"; __t += 1;
	    fix[__t] = "abel"; __t += 1;
	    fix[__t] = "ah"; __t += 1;
	    fix[__t] = "awa"; __t += 1;
	    fix[__t] = "aid"; __t += 1;
	    fix[__t] = "ak"; __t += 1;
	    fix[__t] = "ala"; __t += 1;
	    fix[__t] = "ale"; __t += 1; 
	    fix[__t] = "alia"; __t += 1;
	    fix[__t] = "anda"; __t += 1;
	    fix[__t] = "ava"; __t += 1;
	    fix[__t] = "ath"; __t += 1;
	    fix[__t] = "alis"; __t += 1;
	    fix[__t] = "age"; __t += 1;
	    fix[__t] = "all"; __t += 1;
	    fix[__t] = "ama"; __t += 1;
	    fix[__t] = "ajo"; __t += 1;
	    fix[__t] = "ad"; __t += 1;
	    fix[__t] = "ahn"; __t += 1;
	    fix[__t] = "an"; __t += 1;
	    fix[__t] = "ana"; __t += 1;
	    fix[__t] = "and"; __t += 1;
	    fix[__t] = "ans"; __t += 1;
	    fix[__t] = "ant"; __t += 1;
	    fix[__t] = "at"; __t += 1;
	    fix[__t] = "ao"; __t += 1;
	    fix[__t] = "air"; __t += 1;
	    fix[__t] = "ar"; __t += 1;
	    fix[__t] = "ara"; __t += 1;
	    fix[__t] = "ari"; __t += 1;
	    fix[__t] = "axi"; __t += 1;
	    fix[__t] = "aan"; __t += 1;
	    fix[__t] = "as"; __t += 1;
	    fix[__t] = "athe"; __t += 1;
	    fix[__t] = "ati"; __t += 1;
	    fix[__t] = "auri"; __t += 1;
	    fix[__t] = "ax"; __t += 1;
	    fix[__t] = "aii"; __t += 1;
	    fix[__t] = "ay"; __t += 1;
	    fix[__t] = "ain"; __t += 1;
	    fix[__t] = "ard"; __t += 1;
	    fix[__t] = "aris"; __t += 1;
	    fix[__t] = "amar"; __t += 1;
	    fix[__t] = "ano"; __t += 1;
	    fix[__t] = "arius"; __t += 1;
	    fix[__t] = "aran"; __t += 1;
	    fix[__t] = "ado"; __t += 1;
	    fix[__t] = "aem"; __t += 1;
	    fix[__t] = "ali"; __t += 1;
	    fix[__t] = "ante"; __t += 1;
	    fix[__t] = "arde"; __t += 1;
	    fix[__t] = "arte"; __t += 1;
	    fix[__t] = "aha"; __t += 1;
	    fix[__t] = "asie"; __t += 1;
	    fix[__t] = "aux"; __t += 1;
	    fix[__t] = "aeth"; __t += 1;
	    fix[__t] = "am"; __t += 1;
	    fix[__t] = "abi"; __t += 1;
	    fix[__t] = "aro"; __t += 1;
	    fix[__t] = "aeru"; __t += 1;
	    fix[__t] = "ares"; __t += 1;
	    fix[__t] = "ake"; __t += 1;
	    fix[__t] = "aku"; __t += 1;
	    fix[__t] = "ashi"; __t += 1;
	    fix[__t] = "asho"; __t += 1;
	    fix[__t] = "atta"; __t += 1;
	    fix[__t] = "anai"; __t += 1;
	    fix[__t] = "ane"; __t += 1;
	    fix[__t] = "aury"; __t += 1;
	    fix[__t] = "asu"; __t += 1;
	    fix[__t] = "aki"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "e"; __t += 1;
	    fix[__t] = "ero"; __t += 1;
	    fix[__t] = "esto"; __t += 1;
	    fix[__t] = "ena"; __t += 1;
	    fix[__t] = "ele"; __t += 1;
	    fix[__t] = "ene"; __t += 1;
	    fix[__t] = "eda"; __t += 1;
	    fix[__t] = "est"; __t += 1;
	    fix[__t] = "ern"; __t += 1;
	    fix[__t] = "ex"; __t += 1;
	    fix[__t] = "eus"; __t += 1;
	    fix[__t] = "er"; __t += 1;
	    fix[__t] = "ec"; __t += 1;
	    fix[__t] = "eki"; __t += 1;
	    fix[__t] = "en"; __t += 1;
	    fix[__t] = "eis"; __t += 1;
	    fix[__t] = "enis"; __t += 1;
	    fix[__t] = "enria"; __t += 1;
	    fix[__t] = "enra"; __t += 1;
	    fix[__t] = "eos"; __t += 1;
	    fix[__t] = "eor"; __t += 1;
	    fix[__t] = "ex"; __t += 1;
	    fix[__t] = "eth"; __t += 1;
	    fix[__t] = "erion"; __t += 1;
	    fix[__t] = "eron"; __t += 1;
	    fix[__t] = "eil"; __t += 1;
	    fix[__t] = "ese"; __t += 1;
	    fix[__t] = "eris"; __t += 1;
	    fix[__t] = "een"; __t += 1;
	    fix[__t] = "esis"; __t += 1;
	    fix[__t] = "eva"; __t += 1;
	    fix[__t] = "epto"; __t += 1;
	    fix[__t] = "euse"; __t += 1;
	    fix[__t] = "ella"; __t += 1;
	    fix[__t] = "enor"; __t += 1;
	    fix[__t] = "elia"; __t += 1;
	    fix[__t] = "eart"; __t += 1;
	    fix[__t] = "ent"; __t += 1;
	    fix[__t] = "esu"; __t += 1;
	    fix[__t] = "eole"; __t += 1;
	    fix[__t] = "esa"; __t += 1;
	    fix[__t] = "erie"; __t += 1;
	    fix[__t] = "ecus"; __t += 1;
	    fix[__t] = "esh"; __t += 1;
	    fix[__t] = "ede"; __t += 1;
	    fix[__t] = "ellir"; __t += 1;
	    fix[__t] = "ette"; __t += 1;
	    fix[__t] = "ey"; __t += 1;
	    fix[__t] = "entia"; __t += 1;
	    fix[__t] = "eya"; __t += 1;
	    fix[__t] = "eli"; __t += 1;
	    fix[__t] = "et"; __t += 1;
	    fix[__t] = "eon"; __t += 1;
	    fix[__t] = "eal"; __t += 1;
	    fix[__t] = "ebi"; __t += 1;
	    fix[__t] = "ekka"; __t += 1;
	    fix[__t] = "ek"; __t += 1;
	    fix[__t] = "eces"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "i" __t += 1;
	    fix[__t] = "ica"; __t += 1;
	    fix[__t] = "ici"; __t += 1;
	    fix[__t] = "isto"; __t += 1;
	    fix[__t] = "ino"; __t += 1;
	    fix[__t] = "ina"; __t += 1;
	    fix[__t] = "ini"; __t += 1;
	    fix[__t] = "ito"; __t += 1;
	    fix[__t] = "ii"; __t += 1;
	    fix[__t] = "ii"; __t += 1;
	    fix[__t] = "ii"; __t += 1;
	    fix[__t] = "ia"; __t += 1;
	    fix[__t] = "io"; __t += 1;
	    fix[__t] = "ime"; __t += 1;
	    fix[__t] = "ima"; __t += 1;
	    fix[__t] = "ir"; __t += 1;
	    fix[__t] = "iad"; __t += 1;
	    fix[__t] = "id"; __t += 1;
	    fix[__t] = "ios"; __t += 1;
	    fix[__t] = "ius"; __t += 1;
	    fix[__t] = "ier"; __t += 1;
	    fix[__t] = "in"; __t += 1;
	    fix[__t] = "iin"; __t += 1;
	    fix[__t] = "is"; __t += 1;
	    fix[__t] = "iv"; __t += 1;
	    fix[__t] = "ic"; __t += 1;
	    fix[__t] = "ian"; __t += 1;
	    fix[__t] = "idia"; __t += 1;
	    fix[__t] = "ion"; __t += 1;
	    fix[__t] = "il"; __t += 1;
	    fix[__t] = "ix"; __t += 1;
	    fix[__t] = "iny"; __t += 1;
	    fix[__t] = "itia"; __t += 1;
	    fix[__t] = "ibel"; __t += 1;
	    fix[__t] = "ile"; __t += 1;
		fix[__t] = "iles"; __t += 1;
	    fix[__t] = "ilon"; __t += 1;
	    fix[__t] = "ictis"; __t += 1;
	    fix[__t] = "ind"; __t += 1;
	    fix[__t] = "ich"; __t += 1;
	    fix[__t] = "itica"; __t += 1;
	    fix[__t] = "icus"; __t += 1;
	    fix[__t] = "inda"; __t += 1;
	    fix[__t] = "ine"; __t += 1;
	    fix[__t] = "iolic"; __t += 1;
	    fix[__t] = "iba"; __t += 1;
	    fix[__t] = "ida"; __t += 1;
	    fix[__t] = "ika"; __t += 1;
	    fix[__t] = "iki"; __t += 1;
	    fix[__t] = "iya"; __t += 1;
	    fix[__t] = "ikao"; __t += 1;
	    fix[__t] = "iri"; __t += 1;
	    fix[__t] = "ites"; __t += 1;
	    fix[__t] = "imo"; __t += 1;
	    fix[__t] = "ita"; __t += 1;
	    fix[__t] = "iyo"; __t += 1;
	    fix[__t] = "ira"; __t += 1;
	    fix[__t] = "istu"; __t += 1;
	    fix[__t] = "ippe"; __t += 1;
	    fix[__t] = "ilen"; __t += 1;
	    fix[__t] = "ist"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "o"; __t += 1;
	    fix[__t] = "ori"; __t += 1;
	    fix[__t] = "ora"; __t += 1;
	    fix[__t] = "opa"; __t += 1;
	    fix[__t] = "oor"; __t += 1;
	    fix[__t] = "ona"; __t += 1;
	    fix[__t] = "ope"; __t += 1;
	    fix[__t] = "one"; __t += 1;
	    fix[__t] = "oo"; __t += 1;
	    fix[__t] = "on"; __t += 1;
	    fix[__t] = "ord"; __t += 1;
	    fix[__t] = "oth"; __t += 1;
	    fix[__t] = "os"; __t += 1;
	    fix[__t] = "or"; __t += 1;
	    fix[__t] = "ota"; __t += 1;
	    fix[__t] = "ok"; __t += 1;
	    fix[__t] = "oid"; __t += 1;
	    fix[__t] = "ule"; __t += 1;
	    fix[__t] = "ol"; __t += 1;
	    fix[__t] = "ox"; __t += 1;
	    fix[__t] = "oxi"; __t += 1;
	    fix[__t] = "odos"; __t += 1;
	    fix[__t] = "opia"; __t += 1;
	    fix[__t] = "oka"; __t += 1;
	    fix[__t] = "ont"; __t += 1;
	    fix[__t] = "oris"; __t += 1;
	    fix[__t] = "ore"; __t += 1;
	    fix[__t] = "onis"; __t += 1;
	    fix[__t] = "old"; __t += 1;
	    fix[__t] = "olf"; __t += 1;
	    fix[__t] = "olos"; __t += 1;
	    fix[__t] = "orka"; __t += 1;
	    fix[__t] = "osis"; __t += 1;
	    fix[__t] = "oria"; __t += 1;
	    fix[__t] = "orea"; __t += 1;
	    fix[__t] = "olai"; __t += 1;
	    fix[__t] = "olic"; __t += 1;
	    fix[__t] = "ote"; __t += 1;
	    fix[__t] = "our"; __t += 1;
	    fix[__t] = "oon"; __t += 1;
	    fix[__t] = "osu"; __t += 1;
	    fix[__t] = "oku"; __t += 1;
	    fix[__t] = "orn"; __t += 1;
	    fix[__t] = "oft"; __t += 1;
	    fix[__t] = "oros"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "u"; __t += 1;
	    fix[__t] = "uma"; __t += 1;
	    fix[__t] = "une"; __t += 1;
	    fix[__t] = "ua"; __t += 1;
	    fix[__t] = "una"; __t += 1;
	    fix[__t] = "ium"; __t += 1;
	    fix[__t] = "ula"; __t += 1;
	    fix[__t] = "ugo"; __t += 1;
	    fix[__t] = "ura"; __t += 1;
	    fix[__t] = "uni"; __t += 1;
	    fix[__t] = "us"; __t += 1;
	    fix[__t] = "urn"; __t += 1;
	    fix[__t] = "urus"; __t += 1;
	    fix[__t] = "un"; __t += 1;
	    fix[__t] = "ues"; __t += 1;
	    fix[__t] = "und"; __t += 1;
	    fix[__t] = "ux"; __t += 1;
	    fix[__t] = "use"; __t += 1;
	    fix[__t] = "uk"; __t += 1;
	    fix[__t] = "unni"; __t += 1;
	    fix[__t] = "uum"; __t += 1;
	    fix[__t] = "uchi"; __t += 1;
	    fix[__t] = "ude"; __t += 1;
	    fix[__t] = "uda"; __t += 1;
	    fix[__t] = "ugi"; __t += 1;
	    fix[__t] = "uki"; __t += 1;
	    fix[__t] = "ury"; __t += 1;
	    fix[__t] = "uka"; __t += 1;
	    fix[__t] = "uin"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	}
	//END VOWEL

	if get_type = 1{
	t_sec = round(random_range(0,18)); sec = 0;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "grad"; __t += 1;

	    fix[__t] = "b"; __t += 1;
	    fix[__t] = "bii"; __t += 1;
	    fix[__t] = "bai"; __t += 1;
	    fix[__t] = "bau"; __t += 1;
	    fix[__t] = "bae"; __t += 1;
	    fix[__t] = "beu"; __t += 1;
	    fix[__t] = "bes"; __t += 1;
	    fix[__t] = "bas"; __t += 1;
	    fix[__t] = "bis"; __t += 1;
	    fix[__t] = "ban"; __t += 1;
	    fix[__t] = "bos"; __t += 1;
	    fix[__t] = "bel"; __t += 1;
	    fix[__t] = "bar"; __t += 1;
	    fix[__t] = "bria"; __t += 1;
	    fix[__t] = "brae"; __t += 1;
	    fix[__t] = "brai"; __t += 1;
	    fix[__t] = "bue"; __t += 1;
	    fix[__t] = "bu"; __t += 1;
	    fix[__t] = "bel"; __t += 1;
	    fix[__t] = "boo"; __t += 1;
	    fix[__t] = "bui"; __t += 1;
	    fix[__t] = "buki"; __t += 1;
	    fix[__t] = "bruk"; __t += 1;
	    fix[__t] = "boro"; __t += 1;
	    fix[__t] = "bora"; __t += 1;
	_val = round(random_range(0,__t-1));e = 1;
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "cii"; __t += 1;
	    fix[__t] = "cia"; __t += 1;
	    fix[__t] = "cha"; __t += 1;
	    fix[__t] = "cali"; __t += 1;
	    fix[__t] = "cala"; __t += 1;
	    fix[__t] = "cae"; __t += 1;
	    fix[__t] = "char"; __t += 1;
	    fix[__t] = "chi"; __t += 1;
	    fix[__t] = "chae"; __t += 1; 
	    fix[__t] = "chai"; __t += 1;
	    fix[__t] = "chu"; __t += 1;
	    fix[__t] = "co"; __t += 1;
	    fix[__t] = "ca"; __t += 1;
	    fix[__t] = "chor"; __t += 1;
	    fix[__t] = "cadia"; __t += 1;
	    fix[__t] = "cium"; __t += 1;
		fix[__t] = "cian"; __t += 1;
		fix[__t] = "cias"; __t += 1;
		fix[__t] = "cis"; __t += 1;
	    fix[__t] = "clid"; __t += 1;
	    fix[__t] = "chi"; __t += 1;
	    fix[__t] = "ctus"; __t += 1;
	    fix[__t] = "cina"; __t += 1;
	    fix[__t] = "city"; __t += 1;
	    fix[__t] = "cru"; __t += 1;
	    fix[__t] = "cea"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "d"; __t += 1;
	    fix[__t] = "do"; __t += 1;
	    fix[__t] = "dia"; __t += 1;
	    fix[__t] = "dai"; __t += 1;
	    fix[__t] = "dae"; __t += 1;
	    fix[__t] = "da"; __t += 1;
	    fix[__t] = "don"; __t += 1;
	    fix[__t] = "dan"; __t += 1;
	    fix[__t] = "dos"; __t += 1;
	    fix[__t] = "dus"; __t += 1;
	    fix[__t] = "das"; __t += 1;
	    fix[__t] = "dar"; __t += 1;
	    fix[__t] = "der"; __t += 1;
	    fix[__t] = "dor"; __t += 1;
	    fix[__t] = "diil"; __t += 1;
	    fix[__t] = "dian"; __t += 1;
	    fix[__t] = "dra"; __t += 1;
	    fix[__t] = "dii"; __t += 1;
	    fix[__t] = "den"; __t += 1;
	    fix[__t] = "dox"; __t += 1;
	    fix[__t] = "desu"; __t += 1;
	    fix[__t] = "doc"; __t += 1;
		fix[__t] = "dow"; __t += 1;
	    fix[__t] = "dak"; __t += 1;
	    fix[__t] = "desa"; __t += 1;
	    fix[__t] = "dav"; __t += 1;
	    fix[__t] = "dote"; __t += 1;
	    fix[__t] = "dros"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;

	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "fa"; __t += 1;
	    fix[__t] = "fe"; __t += 1;
	    fix[__t] = "fi"; __t += 1;
	    fix[__t] = "fu"; __t += 1;
	    fix[__t] = "fo"; __t += 1;
	    fix[__t] = "far"; __t += 1;
	    fix[__t] = "fen"; __t += 1;
	    fix[__t] = "fron"; __t += 1;
	    fix[__t] = "flora"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "g"; __t += 1;
	    fix[__t] = "go"; __t += 1;
	    fix[__t] = "ga"; __t += 1;
	    fix[__t] = "gard"; __t += 1;
	    fix[__t] = "gae"; __t += 1;
	    fix[__t] = "gaea"; __t += 1;
	    fix[__t] = "gen"; __t += 1;
	    fix[__t] = "gaia"; __t += 1;
	    fix[__t] = "gai"; __t += 1;
	    fix[__t] = "gata"; __t += 1;
	    fix[__t] = "gna"; __t += 1;
	    fix[__t] = "gua"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "hai"; __t += 1;
	    fix[__t] = "helm"; __t += 1;
	    fix[__t] = "heart"; __t += 1;
	    fix[__t] = "hima"; __t += 1;
	    fix[__t] = "har"; __t += 1;
	    fix[__t] = "hime"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "ju"; __t += 1;
	    fix[__t] = "ji"; __t += 1;
	    fix[__t] = "jo"; __t += 1;
	    fix[__t] = "ja"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;

	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "jii"; __t += 1;
	    fix[__t] = "jor"; __t += 1;
	    fix[__t] = "k"; __t += 1;
	    fix[__t] = "ku"; __t += 1;
	    fix[__t] = "ka"; __t += 1;
	    fix[__t] = "kia"; __t += 1;
	    fix[__t] = "ko"; __t += 1;
	    fix[__t] = "kyo"; __t += 1;
	    fix[__t] = "kku"; __t += 1;
	    fix[__t] = "ki"; __t += 1;
	    fix[__t] = "keth"; __t += 1;
	    fix[__t] = "kos"; __t += 1;
	    fix[__t] = "kar"; __t += 1;
	    fix[__t] = "kis"; __t += 1;
	    fix[__t] = "kun"; __t += 1;
	    fix[__t] = "kol"; __t += 1;
	    fix[__t] = "kima"; __t += 1;
	    fix[__t] = "kon"; __t += 1;  
	    fix[__t] = "kar"; __t += 1;  
	    fix[__t] = "ky"; __t += 1;
	    fix[__t] = "kai"; __t += 1;
	    fix[__t] = "kae"; __t += 1;
	    fix[__t] = "kaia"; __t += 1;
	    fix[__t] = "kura"; __t += 1;
	    fix[__t] = "kan"; __t += 1;
	    fix[__t] = "koro"; __t += 1;
	    fix[__t] = "kari"; __t += 1;
	    fix[__t] = "kara"; __t += 1;
	    fix[__t] = "kimi"; __t += 1;
	    fix[__t] = "kiri"; __t += 1;
	    fix[__t] = "koi"; __t += 1;
	    fix[__t] = "komo"; __t += 1;
	    fix[__t] = "kou"; __t += 1;
	    fix[__t] = "koi"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "l"; __t += 1;
	    fix[__t] = "lma"; __t += 1;
	    fix[__t] = "lia"; __t += 1;
	    fix[__t] = "llia"; __t += 1;
	    fix[__t] = "lore"; __t += 1;
	    fix[__t] = "la"; __t += 1;
	    fix[__t] = "llir"; __t += 1;
	    fix[__t] = "lis"; __t += 1;
	    fix[__t] = "lo"; __t += 1;
	    fix[__t] = "li"; __t += 1;
	    fix[__t] = "lag"; __t += 1;
	    fix[__t] = "lex"; __t += 1;
	    fix[__t] = "lax"; __t += 1;
	    fix[__t] = "lum"; __t += 1;
	    fix[__t] = "len"; __t += 1;
	    fix[__t] = "las"; __t += 1;
	    fix[__t] = "los"; __t += 1;
	    fix[__t] = "lhar"; __t += 1;
	    fix[__t] = "lae"; __t += 1;
	    fix[__t] = "lai"; __t += 1;
	    fix[__t] = "lat"; __t += 1;
	    fix[__t] = "llum"; __t += 1;
	    fix[__t] = "lahad"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "m"; __t += 1;
	    fix[__t] = "ma"; __t += 1;
	    fix[__t] = "me"; __t += 1;
	    fix[__t] = "meda"; __t += 1;
	    fix[__t] = "mari"; __t += 1;
	    fix[__t] = "mala"; __t += 1;
	    fix[__t] = "mora"; __t += 1;
	    fix[__t] = "maea"; __t += 1;
	    fix[__t] = "mera"; __t += 1;
	    fix[__t] = "mos"; __t += 1;
	    fix[__t] = "mo"; __t += 1;
	    fix[__t] = "mor"; __t += 1;
	    fix[__t] = "mar"; __t += 1;
	    fix[__t] = "meis"; __t += 1;
	    fix[__t] = "mon"; __t += 1;
	    fix[__t] = "mas"; __t += 1;
	    fix[__t] = "mia"; __t += 1;
	    fix[__t] = "mae"; __t += 1;
	    fix[__t] = "mal"; __t += 1;
	    fix[__t] = "muh"; __t += 1;
	    fix[__t] = "mori"; __t += 1;
	    fix[__t] = "masu"; __t += 1;
	    fix[__t] = "mai"; __t += 1;
	    fix[__t] = "mesa"; __t += 1;
	    fix[__t] = "mist"; __t += 1;
	    fix[__t] = "moor"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "n"; __t += 1;
	    fix[__t] = "nia"; __t += 1;
	    fix[__t] = "nu"; __t += 1;
	    fix[__t] = "ne"; __t += 1;
	    fix[__t] = "na"; __t += 1;
	    fix[__t] = "nid"; __t += 1;
	    fix[__t] = "nde"; __t += 1;
	    fix[__t] = "ndo"; __t += 1;
	    fix[__t] = "ni"; __t += 1;
	    fix[__t] = "nna"; __t += 1;
	    fix[__t] = "nis"; __t += 1;
	    fix[__t] = "nos"; __t += 1;
	    fix[__t] = "nus"; __t += 1;
	    fix[__t] = "nor"; __t += 1;
	    fix[__t] = "nan"; __t += 1;
	    fix[__t] = "nua"; __t += 1;
	    fix[__t] = "nae"; __t += 1;
	    fix[__t] = "nox"; __t += 1;
	    fix[__t] = "non"; __t += 1;
	    fix[__t] = "ndell"; __t += 1;
	    fix[__t] = "naid"; __t += 1;
	    fix[__t] = "naev"; __t += 1;
	    fix[__t] = "naeva"; __t += 1;
	    fix[__t] = "nab"; __t += 1;
	    fix[__t] = "nax"; __t += 1;
	    fix[__t] = "nix"; __t += 1;
	    fix[__t] = "nyos"; __t += 1;
	    fix[__t] = "nea"; __t += 1;
	    fix[__t] = "nii"; __t += 1;
	    fix[__t] = "ney"; __t += 1;
	    fix[__t] = "nui"; __t += 1;
	    fix[__t] = "nai"; __t += 1;
	    fix[__t] = "nhelm"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	
	
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "p"; __t += 1;
	    fix[__t] = "pe"; __t += 1;
	    fix[__t] = "pae"; __t += 1;
	    fix[__t] = "pia"; __t += 1;
		fix[__t] = "pia"; __t += 1;
		fix[__t] = "pia"; __t += 1;
	    fix[__t] = "pa"; __t += 1;
	    fix[__t] = "pra"; __t += 1;
	    fix[__t] = "phae"; __t += 1;
	    fix[__t] = "pit"; __t += 1;
	    fix[__t] = "pin"; __t += 1;
	    fix[__t] = "par"; __t += 1;
	    fix[__t] = "pal"; __t += 1;
		fix[__t] = "pan"; __t += 1;
	    fix[__t] = "per"; __t += 1;
	    fix[__t] = "pos"; __t += 1;
	    fix[__t] = "pest"; __t += 1;
	    fix[__t] = "phron"; __t += 1;
	    fix[__t] = "polis"; __t += 1;
	    fix[__t] = "phia"; __t += 1;
	    fix[__t] = "ptor"; __t += 1;
	    fix[__t] = "piter"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "ro"; __t += 1;
	    fix[__t] = "ra"; __t += 1;
	    fix[__t] = "re"; __t += 1;
	    fix[__t] = "rho"; __t += 1;
	    fix[__t] = "ri"; __t += 1;
	    fix[__t] = "rae"; __t += 1;
	    fix[__t] = "rii"; __t += 1;
	    fix[__t] = "rth"; __t += 1;
	    fix[__t] = "rai"; __t += 1;
	    fix[__t] = "rig"; __t += 1;
	    fix[__t] = "rius"; __t += 1;
	    fix[__t] = "ris"; __t += 1;
	    fix[__t] = "ros"; __t += 1;
	    fix[__t] = "rok"; __t += 1;
	    fix[__t] = "ru"; __t += 1;
	    fix[__t] = "rom"; __t += 1;
	    fix[__t] = "ron"; __t += 1;
	    fix[__t] = "rid"; __t += 1;
	    fix[__t] = "rak"; __t += 1;
	    fix[__t] = "ria"; __t += 1;
	    fix[__t] = "rad"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "s"; __t += 1;
	    fix[__t] = "sta"; __t += 1;
	    fix[__t] = "ste"; __t += 1;
	    fix[__t] = "ssa"; __t += 1;
	    fix[__t] = "shi"; __t += 1;
	    fix[__t] = "sei"; __t += 1;
	    fix[__t] = "shei"; __t += 1;
	    fix[__t] = "shire"; __t += 1;
	    fix[__t] = "shia"; __t += 1;
	    fix[__t] = "sis"; __t += 1;
	    fix[__t] = "sol"; __t += 1;
	    fix[__t] = "ster"; __t += 1;
	    fix[__t] = "stra"; __t += 1;
	    fix[__t] = "suk"; __t += 1;
	    fix[__t] = "sak"; __t += 1;
	    fix[__t] = "stor"; __t += 1;
	    fix[__t] = "sae"; __t += 1;
	    fix[__t] = "sau"; __t += 1;
	    fix[__t] = "sho"; __t += 1;
	    fix[__t] = "sha"; __t += 1;
	    fix[__t] = "saki"; __t += 1;
	    fix[__t] = "sama"; __t += 1;
	    fix[__t] = "sia"; __t += 1;
	    fix[__t] = "stos"; __t += 1;
	    fix[__t] = "shii"; __t += 1;
	    fix[__t] = "su"; __t += 1;
	    fix[__t] = "sii"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
		fix[__t] = "tros"; __t += 1;
	    fix[__t] = "t"; __t += 1;
	    fix[__t] = "ta"; __t += 1;
	    fix[__t] = "taa"; __t += 1;
	    fix[__t] = "tae"; __t += 1;
	    fix[__t] = "taka"; __t += 1;
	    fix[__t] = "taki"; __t += 1;
	    fix[__t] = "tama"; __t += 1;
	    fix[__t] = "tan"; __t += 1;
	    fix[__t] = "tao"; __t += 1;
	    fix[__t] = "tar"; __t += 1;
	    fix[__t] = "tas"; __t += 1;
	    fix[__t] = "tau"; __t += 1;
	    fix[__t] = "te"; __t += 1;
	    fix[__t] = "tea"; __t += 1;
	    fix[__t] = "tel"; __t += 1;
	    fix[__t] = "tem"; __t += 1;
	    fix[__t] = "ter"; __t += 1;
	    fix[__t] = "tex"; __t += 1;
	    fix[__t] = "th"; __t += 1;
	    fix[__t] = "thal"; __t += 1;
	    fix[__t] = "thea"; __t += 1;
	    fix[__t] = "thens"; __t += 1;
	    fix[__t] = "thi"; __t += 1;
	    fix[__t] = "thia"; __t += 1;
	    fix[__t] = "thor"; __t += 1;
	    fix[__t] = "thos"; __t += 1;
	    fix[__t] = "ti"; __t += 1;
	    fix[__t] = "tia"; __t += 1;
	    fix[__t] = "tica"; __t += 1;
	    fix[__t] = "tie"; __t += 1;
	    fix[__t] = "tii"; __t += 1;
	    fix[__t] = "tis"; __t += 1;
	    fix[__t] = "tium"; __t += 1;
	    fix[__t] = "to"; __t += 1;
	    fix[__t] = "tor"; __t += 1;
	    fix[__t] = "tori"; __t += 1;
	    fix[__t] = "trix"; __t += 1;
	    fix[__t] = "tsu"; __t += 1;
	    fix[__t] = "tude"; __t += 1;
	    fix[__t] = "turn"; __t += 1;
	    fix[__t] = "tus"; __t += 1;
	    fix[__t] = "tuu"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;

	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "v"; __t += 1;
	    fix[__t] = "ve"; __t += 1;
	    fix[__t] = "va"; __t += 1;
	    fix[__t] = "vae"; __t += 1;
	    fix[__t] = "vi"; __t += 1;
	    fix[__t] = "via"; __t += 1;
	    fix[__t] = "vea"; __t += 1;
	    fix[__t] = "vie"; __t += 1;
	    fix[__t] = "vo"; __t += 1;
	    fix[__t] = "vei" __t += 1;
	    fix[__t] = "ven"; __t += 1;
	    fix[__t] = "van"; __t += 1;
	    fix[__t] = "vin"; __t += 1;
	    fix[__t] = "var"; __t += 1;
	    fix[__t] = "vor"; __t += 1;
	    fix[__t] = "vos"; __t += 1;
	    fix[__t] = "ver"; __t += 1;
	    fix[__t] = "vir"; __t += 1;
	    fix[__t] = "vic"; __t += 1;
	    fix[__t] = "vec"; __t += 1;
	    fix[__t] = "vion"; __t += 1;
	    fix[__t] = "vius"; __t += 1;
	    fix[__t] = "vil"; __t += 1;
	    fix[__t] = "vis"; __t += 1;
	    fix[__t] = "vii"; __t += 1;
	    fix[__t] = "vus"; __t += 1;
	    fix[__t] = "vega"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "x"; __t += 1;
	    fix[__t] = "xa"; __t += 1;
		fix[__t] = "xia"; __t += 1;
	    fix[__t] = "xis"; __t += 1;
	    fix[__t] = "xir"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "ya"; __t += 1;
	    fix[__t] = "yo"; __t += 1;
	    fix[__t] = "yu"; __t += 1;
	    fix[__t] = "yor"; __t += 1;
	    fix[__t] = "yun"; __t += 1;
	    fix[__t] = "you"; __t += 1;
	    fix[__t] = "yl"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	//////////////////////////A
	if t_sec = sec{__t = 0; 
	    fix[__t] = "z"; __t += 1;
	    fix[__t] = "ze"; __t += 1;
	    fix[__t] = "zo"; __t += 1;
	    fix[__t] = "zon"; __t += 1;
	    fix[__t] = "zen"; __t += 1;
	    fix[__t] = "zu"; __t += 1;
	    fix[__t] = "zark"; __t += 1;
	    fix[__t] = "zar"; __t += 1;
	_val = round(random_range(0,__t-1));
	} sec += 1;
	}

	_val = fix[_val]
	_name = string_insert(_name,_val,0);
	//name = string_insert(name," ",0);



}
