/// @description exped_lines() -> THE DIARY's lines (his ask, 2026-09-12:
/// "lots of fun little lore bits... dumb funny... but with logic and
/// structure so there is consistency and continuity"). Every entry is a
/// TEMPLATE with GATES; exped_say picks one per beat and fills the slots.
///
/// THE SHAPE (the register: a dim, self-aware narrator, deadpan,
/// anticlimax, literal-minded, the world never reacts, no exclamation
/// marks, one joke a line, the truth line above it always says plainly
/// what happened):
///   b       the beat - depart / travel / land / find / rest / trap /
///           fight_open / fight_won / fight_lost / return / home / sky
///   t       the text; slots {name} {planet} {biome} {foe} {item} {partner}
///   pers    only this personality says it (sprite_personalities names)
///   biome   only on this world (exped_biomes names)
///   party   1 = only alone, 2 = only with a partner along
///   bond    with a partner: 1 strangers / 2 mates / 3 inseparable
///   hp      "low" = only under 40% hp
///   routed  only when the trip is / is not routed
///   opens   starts a THREAD on the trip (a setup); refused if already open
///   closes  needs that thread open, and closes it (the payoff) - closers
///           are preferred whenever one qualifies, and the trip's end
///           closes what is left. THIS is what makes it a diary rather
///           than a list of jokes: a line in room 2 that room 4 answers
///   need    a MEMORY gate (exped_say): "first" (the sprite's first trip),
///           "third" (third or later), "revisit" (this planet again),
///           "routed_before", "streak3" (three trips unrouted), "wins3",
///           "retired" (someone has been swapped out - {retired} names them)
///   w       weight (default 1) - the specific beats the generic
///   THE SITUATION'S GATES (the voice pass, 2026-09-15):
///   night   true / false (where the crew stands)
///   wx      "rain" / "snow" / "fog" / "wind" / "storm" / "clear"
///   haz     "dark" / "damp" / "heat" / "cold" (the hazard where they stand, cbt_hazards)
///   cls     the speaker's class key (warrior / mage / rogue / cleric / ranger)
///   ppers   the partner's personality
///   kind    the place's kind (region_kinds: forest / marsh / crypt ...)
///   qk      the quest's kind (exped_quest_gen's) or "explore"
///   poor    true = the pocket is empty
///   lv      "low" (1-2) / "high" (6+)
///   more slots: {place} where they stand, {goal} the quest's last stop,
///   {region}, {who} the quest's merchant / cargo / lost one / boss, {wx}, {cls}
///   THE WORLD'S GATES (planet_props): moons 0..4 (the count), moonless true, ringed true
///   NEW BEATS: road / night / dawn / weather / inn / poor / tavern / shop /
///   bought / shrine / mine / ruin / wild / camp / delve / hazard / meet /
///   fetch / found / deliver / boss / wave / chart / lost / levelup / skill
///
/// ⚖️ ORIGINAL LINES, in a register he liked from elsewhere. Add, cut,
/// retune here - the file IS the voice; a line that falls flat is one
/// line to delete.
function exped_lines() {
	static _l = [
		{ b : "depart", t : "{name} packed for every eventuality except the trip." },
		{ b : "depart", t : "{name} left a note for the others. it says \"gone\". it is very thorough." },
		{ b : "depart", t : "departure. {name} waved at the ship for a while before being told to get in it." },
		{ b : "depart", t : "{name} has a plan for {planet}. the plan is to arrive. beyond that, improvisation." },
		{ b : "depart", t : "{name} checked the supplies twice and the snacks nine times." },
		{ b : "depart", t : "the ship made a noise on the way out. {name} has decided it was a happy noise." },
		{ b : "depart", t : "{name} asked where {planet} was. up, apparently. {name} is heading up." },
		{ b : "depart", t : "last thing before leaving: {name} touched the doorframe for luck. the doorframe did not react. that is how luck works." },
		{ b : "depart", t : "{name} was in the ship before anyone said go. no one had said go. no one was going to.", pers : "eager" },
		{ b : "depart", t : "{name} boarded, sat down, and was asleep before the door closed. an efficient start.", pers : "sleepy" },
		{ b : "depart", t : "{name} has been to space before. once. in a dream. it counts.", pers : "smug" },
		{ b : "depart", t : "{name} pressed every button in the ship to learn what they did. two of them did something. the trip has begun regardless.", pers : "curious" },
		{ b : "depart", t : "{name} did not want to go. {name} went. this is the whole story of {name}.", pers : "grumpy" },
		{ b : "depart", t : "{name} named the ship on the way out. the ship is called \"the ship\". it suits her.", pers : "cheerful" },
		{ b : "depart", t : "{name} said goodbye to everyone very quietly, from inside the ship, after it had left.", pers : "shy" },
		{ b : "depart", t : "{name} has brought a bigger bag than the ship. the bag is folded. the plan is not.", pers : "greedy" },
		{ b : "depart", t : "{name}'s first expedition. everything is a first. the ship, the dark, the snacks tasting like the dark.", need : "first", w : 3 },
		{ b : "depart", t : "third time out. {name} has started packing the right things, which takes some of the fun out of it.", need : "third", w : 2 },
		{ b : "depart", t : "{name} has been routed before and has decided this time will be different, in ways that have not been specified.", need : "routed_before", w : 2 },
		{ b : "depart", t : "three trips without running away. {name} is not counting. {name} is counting.", need : "streak3", w : 2 },
		{ b : "travel", t : "day one of the crossing. {name} has named the stars. all of them greg." },
		{ b : "travel", t : "space is mostly nothing, and the nothing is very well organised." },
		{ b : "travel", t : "{name} tried to count the stars, lost count at eleven, and started again from \"many\"." },
		{ b : "travel", t : "the ship hums. {name} hums back. neither of them knows the tune." },
		{ b : "travel", t : "halfway. {name} celebrated by eating tomorrow's ration, then today's, in that order." },
		{ b : "travel", t : "{name} has been practising a landing face in the window. the window is not convinced." },
		{ b : "travel", t : "there was a moment of turbulence. {name} apologised to it." },
		{ b : "travel", t : "{name} watched a dot get slightly bigger for an hour. the dot is {planet}. the hour was worth it, probably." },
		{ b : "travel", t : "{name} slept through the interesting part of space. all of space is the interesting part. {name} slept through space.", pers : "sleepy" },
		{ b : "travel", t : "{name} asked the ship where it was going. the ship said nothing, which {name} took as \"you'll see\".", pers : "curious" },
		{ b : "travel", t : "the view is stars. it has been stars for hours. {name} has requested different stars.", pers : "grumpy" },
		{ b : "travel", t : "{name} spotted {planet} first. there was no one else to spot it. still counts.", pers : "smug" },
		{ b : "travel", t : "{name} has been talking to the snacks. the snacks are good listeners and getting fewer.", pers : "cheerful" },
		{ b : "travel", t : "{name} thought about {retired} today. {retired} would have hated this. {name} is hating it for both of them.", need : "retired", w : 2 },
		{ b : "rest", t : "a quiet room. {name} found a mark on the wall that looked like {retired}'s handwriting. it was a crack. {name} sat with it a while anyway.", need : "retired", w : 2 },
		{ b : "land", t : "{retired} always said {name} would end up somewhere like {planet}. {retired} meant it as a warning.", need : "retired", w : 2 },
		{ b : "home", t : "home. someone had used {retired}'s old spot. {name} has moved them, gently, and said nothing.", need : "retired", w : 2 },
		{ b : "land", t : "landed. the ground is here, as advertised." },
		{ b : "land", t : "{name} stepped out, breathed in, and coughed for a bit. the air is real, then." },
		{ b : "land", t : "first footprint on {planet}. {name} went back and made it deeper so it would last." },
		{ b : "land", t : "{planet} has weather. {name} is not sure which kind yet, but it is happening." },
		{ b : "land", t : "arrived. {name} has planted a flag. the flag is a stick. the stick is planted." },
		{ b : "land", t : "the landing was smooth if you don't count the landing." },
		{ b : "land", t : "landed on {planet}. it is a rock. {name} respects that.", biome : "stone", w : 2 },
		{ b : "land", t : "{planet} is grey in every direction. {name} has picked a direction and is calling it forward.", biome : "stone", w : 2 },
		{ b : "land", t : "the rocks here are big. {name} has decided not to compete.", biome : "stone", w : 2 },
		{ b : "land", t : "everything on {planet} is a rock, including, {name} suspects, the sky.", biome : "stone", w : 2 },
		{ b : "land", t : "the ground on {planet} breathes. {name} has decided not to mention this to the ground.", biome : "living", w : 2 },
		{ b : "land", t : "something on {planet} said hello. {name} said hello back. now they are both waiting.", biome : "living", w : 2 },
		{ b : "land", t : "the plants here lean toward {name}. {name} is trying to take it as a compliment.", biome : "living", w : 2 },
		{ b : "land", t : "{planet} smells like a greenhouse that has opinions.", biome : "living", w : 2 },
		{ b : "land", t : "ruins. someone built all this and then left, which {name} considers a very relatable decision.", biome : "ruined", w : 2 },
		{ b : "land", t : "there are doors on {planet} with nothing behind them. {name} knocked anyway. manners.", biome : "ruined", w : 2 },
		{ b : "land", t : "whoever lived on {planet} left in a hurry and took the roofs.", biome : "ruined", w : 2 },
		{ b : "land", t : "{name} found a statue with the face worn off. gave it a face. it looks surprised.", biome : "ruined", w : 2 },
		{ b : "land", t : "{planet} is cold in a way that feels personal.", biome : "ice", w : 2 },
		{ b : "land", t : "the snow on {planet} squeaks. {name} has apologised to it twice.", biome : "ice", w : 2 },
		{ b : "land", t : "{name} tried to make a snow version of {name}. it looked better. left it.", biome : "ice", w : 2 },
		{ b : "land", t : "everything on {planet} is frozen except {name}'s opinion of the cold, which is heating up.", biome : "ice", w : 2 },
		{ b : "land", t : "back on {planet}. the rocks recognise {name}. the feeling is not mutual.", need : "revisit", w : 4 },
		// ======================= THE BIOMES PASS (2026-09-15): ash / ocean / dust / fungal =======================
		{ b : "land", t : "{planet} is black and red and warm through the boots. {name} has decided not to sit down anywhere.", biome : "ash", w : 2 },
		{ b : "land", t : "the ground on {planet} glows in the cracks. {name} has stepped between the cracks with great care and a little dance.", biome : "ash", w : 2 },
		{ b : "land", t : "ash falls on {planet} like slow snow that is wrong. {name} caught some. it was warm. {name} is not doing that again.", biome : "ash", w : 2 },
		{ b : "land", t : "{planet} is mostly sea. {name} landed on the bit that is not and is standing very much in the middle of it.", biome : "ocean", w : 2 },
		{ b : "land", t : "water to every horizon and one road. {name} has taken the road, there being no argument.", biome : "ocean", w : 2 },
		{ b : "land", t : "the air on {planet} tastes of salt and the ground is mostly beach. {name} has sand in things already.", biome : "ocean", w : 2 },
		{ b : "land", t : "{planet} is sand. the sand is hot. {name} has confirmed both and would like a hat.", biome : "dust", w : 2 },
		{ b : "land", t : "landed on {planet}. the horizon shimmers. {name} waved at it, in case it was someone.", biome : "dust", w : 2 },
		{ b : "land", t : "dust. dust in the boots, the bag, the diary. {name} has written this down in the dust, on the page.", biome : "dust", w : 2 },
		{ b : "land", t : "the trees on {planet} are not trees. they are mushrooms, the height of trees. {name} has stopped calling them trees, mostly.", biome : "fungal", w : 2 },
		{ b : "land", t : "everything on {planet} is purple and soft and smells of a cellar. {name} likes it and is not sure that is allowed.", biome : "fungal", w : 2 },
		{ b : "land", t : "spores in the air like slow rain. {name} sneezed and the ground sneezed back, a little.", biome : "fungal", w : 2 },
		{ b : "find", t : "found {item}. {name} has no idea what it does and intends to keep it in a pocket until it becomes important." },
		{ b : "find", t : "found {item}. it was under a rock. most things are, if you are willing to lift enough rocks." },
		{ b : "find", t : "found {item}. {name} looked around for the owner, found no one, and became the owner." },
		{ b : "find", t : "found {item} and immediately dropped it, to check it wasn't a trick. it wasn't. picked it up again. still isn't." },
		{ b : "find", t : "found {item}. it was labelled \"do not take\". {name} does not read labels, which has turned out to be a skill." },
		{ b : "find", t : "found {item}. {name} did a small dance. there was no one to see it, which is the best kind of dance." },
		{ b : "find", t : "found {item}. {name} said \"aha\", quietly, in case it was a mistake." },
		{ b : "find", t : "found {item}, wedged in a crack. the crack is fine. the crack has been through worse." },
		{ b : "find", t : "found {item}. {name} has decided it is worth a lot, based on how hard it was to reach." },
		{ b : "find", t : "found {item} exactly where {name} would have hidden it. {name} is now suspicious of {name}." },
		{ b : "find", t : "found {item}. {name} has already spent it three times in {name}'s head.", pers : "greedy" },
		{ b : "find", t : "found {item}. {name} turned it over for a long time. it has two sides. noted.", pers : "curious" },
		{ b : "find", t : "found {item}. {name} said \"finally\" as if it had been promised.", pers : "grumpy" },
		{ b : "find", t : "found {item}. {name} knew it would be here. {name} did not know it would be here.", pers : "smug" },
		{ b : "find", t : "also: a small rock that seemed to be watching. bringing it along. for science, or company.", opens : "rock", w : 2 },
		{ b : "find", t : "there was a sound in the walls that {name} is choosing to call \"the neighbour\".", opens : "neighbour", w : 2 },
		{ b : "rest", t : "{name} picked up a stick. it is a good stick. this is going to be a whole thing.", opens : "stick", w : 2 },
		{ b : "land", t : "{name} has started a collection of interesting pebbles. it is one pebble. it is interesting.", opens : "pebble", w : 2 },
		{ b : "find", t : "the rock has been checked. it is a rock. {name} would appreciate this not being brought up.", closes : "rock" },
		{ b : "rest", t : "the rock fell out of a pocket. {name} went back for it. no one saw.", closes : "rock" },
		{ b : "home", t : "the rock made it home. it has a shelf now. it is still a rock, but a housed one.", closes : "rock" },
		{ b : "rest", t : "update on the neighbour: it was the wind. {name} has forgiven it.", closes : "neighbour" },
		{ b : "home", t : "the neighbour followed {name} to the ship. it is still the wind. it is coming home.", closes : "neighbour" },
		{ b : "trap", t : "the stick broke. {name} is carrying both halves out of respect.", closes : "stick" },
		{ b : "home", t : "the stick has been named. its name is stick. it prefers it.", closes : "stick" },
		{ b : "find", t : "the pebble collection is now two pebbles. the second one is a bit of the first one.", closes : "pebble" },
		{ b : "home", t : "the pebble collection did not survive the trip. it was one pebble. it is somewhere on {planet} now, being interesting alone.", closes : "pebble" },
		{ b : "rest", t : "a quiet room. {name} sat in it and thought about nothing so hard the nothing left." },
		{ b : "rest", t : "rested. {name} lay down for a minute and got up in a different mood, which is the whole point of minutes." },
		{ b : "rest", t : "a calm room. {name} took off both boots, then remembered {name} has no boots, then had a lie down about it." },
		{ b : "rest", t : "{name} found a corner with no drafts and would like to live there. moving on anyway. duty." },
		{ b : "rest", t : "rested here. the wall was warm. {name} has thanked the wall." },
		{ b : "rest", t : "a quiet room. {name} hummed. the room hummed back, a bit late, a bit lower. they left it there." },
		{ b : "rest", t : "sat down. counted the supplies. counted them again in case the first count was rude." },
		{ b : "rest", t : "{name} took a nap and dreamt of {planet}, which was lazy of the dream, as {name} was already there." },
		{ b : "rest", t : "a quiet room. {name} has nothing to add. {name} is asleep.", pers : "sleepy" },
		{ b : "rest", t : "rested for almost a whole minute. {name} is calling it a retreat.", pers : "eager" },
		{ b : "rest", t : "a nice room, {name} admits, with the air of someone admitting to a crime.", pers : "grumpy" },
		{ b : "rest", t : "a quiet room. {name} sat in the middle of it so as not to bother the edges.", pers : "shy" },
		{ b : "trap", t : "stepped on a thing that was clearly a trap, on the grounds that it looked like the only floor." },
		{ b : "trap", t : "a trap. {name} has learned from it. specifically, {name} has learned where it is." },
		{ b : "trap", t : "a dart came out of the wall. {name} caught it, which would have been impressive from the front." },
		{ b : "trap", t : "the floor gave way a little. {name} gave way a lot. everyone has recovered." },
		{ b : "trap", t : "a trap went off. {name} yelled a word that will not be recorded here, out of respect for the diary." },
		{ b : "trap", t : "{name} triggered a trap, then triggered it again to see if the first time was a fluke. it was not a fluke." },
		{ b : "trap", t : "a rock fell. {name} was under it briefly, then next to it. that is progress." },
		{ b : "trap", t : "there was a tripwire. {name} tripped. the wire did its job and {name} did the rest." },
		{ b : "trap", t : "{name} is fine. {name} has said \"i'm fine\" enough times now that it has become a chant.", hp : "low", w : 3 },
		{ b : "trap", t : "another trap. {name} is starting to take {planet} personally.", hp : "low", w : 3 },
		{ b : "trap", t : "{planet} again, and {name} knows where the traps are now. stepped on them in a new order.", need : "revisit", w : 3 },
		{ b : "trap", t : "that was the last one {name} had in them. heading back, at a walk that would like to be a run.", w : 6, routed : true },
		{ b : "fight_open", t : "{foe} blocks the way. {name} has explained that this is a public corridor. {foe} disagrees, physically." },
		{ b : "fight_open", t : "{foe}. {name} has never seen one before and would have been fine keeping it that way." },
		{ b : "fight_open", t : "{foe} stepped out of the dark. {name} stepped back into it. they have swapped, and neither is happy." },
		{ b : "fight_open", t : "{foe} made a noise. {name} made the same noise back, which turns out to mean \"fight\"." },
		{ b : "fight_open", t : "{foe}. {name} said \"nice {foe}\". it is not a nice {foe}." },
		{ b : "fight_open", t : "{foe} appeared. {name} checked behind for help. there was a wall. the wall is neutral." },
		{ b : "fight_open", t : "{foe} is bigger up close. most things are. {name} has decided to be brave from further away." },
		{ b : "fight_open", t : "{foe} and {name} regarded each other. {foe} regarded harder." },
		{ b : "fight_open", t : "{foe}. {name} has beaten worse. {name} cannot name any worse, but has beaten it.", pers : "smug" },
		{ b : "fight_open", t : "{foe} blocks the way. {name} tried \"excuse me\". {foe} is not the excusing sort.", pers : "shy" },
		{ b : "fight_open", t : "{foe} blocks the way. {name} checked it for pockets first. no pockets. now it is a fight.", pers : "greedy" },
		{ b : "fight_open", t : "{foe}. finally. {name} has been swinging at the air for practice and the air was getting bored.", pers : "eager" },
		{ b : "fight_open", t : "{name} has won three fights now and has begun referring to the arm as \"the arm\". {foe} has not been told.", need : "wins3", w : 3 },
		{ b : "fight_won", t : "{foe} has fallen. {name} would like it recorded that the foe started it, and that {name} finished it, eventually, from behind." },
		{ b : "fight_won", t : "{foe} is down. {name} stood over it for a bit, then apologised, then took the room." },
		{ b : "fight_won", t : "won. {name} is going to tell this story better than it happened, and that is the diary's official position too." },
		{ b : "fight_won", t : "{foe} gave up in the end. so did {name}, but slightly later, which is called winning." },
		{ b : "fight_won", t : "the way is clear. {name} has a new limp and a new story and considers this a fair trade." },
		{ b : "fight_won", t : "{foe} is beaten. {name} checked twice. {foe} stayed beaten both times." },
		{ b : "fight_won", t : "{name} hit {foe} until {foe} stopped, which is the whole of the technique." },
		{ b : "fight_won", t : "victory. {name} did a lap of the room. the room is small. it was a short lap." },
		{ b : "fight_lost", t : "{name} performed a tactical retreat at a speed that suggests the tactic was fear." },
		{ b : "fight_lost", t : "{foe} won. {name} left the room, then the corridor, then, on reflection, the planet." },
		{ b : "fight_lost", t : "{name} decided the fight was going badly and stopped attending it." },
		{ b : "fight_lost", t : "routed. {name} would like the record to show {foe} was enormous, and the record will show that, because {name} is holding the pen." },
		{ b : "fight_lost", t : "{name} ran. the running was excellent. the fight before it, less so." },
		{ b : "fight_lost", t : "{foe} chased {name} as far as the door and then lost interest. {name} has not lost interest and is still running." },
		{ b : "return", t : "heading home. {name} has counted the loot four times and got three different answers, all of them \"some\".", routed : false },
		{ b : "return", t : "leaving {planet}. {name} looked back once, for the diary. it was still there.", routed : false },
		{ b : "return", t : "home stretch. {name} is rehearsing the story and has already promoted the rooms to caves and the caves to depths.", routed : false },
		{ b : "return", t : "{name} left {planet} a little tidier than it was found, by taking things from it.", routed : false },
		{ b : "return", t : "the ship again. {name} sat in the same seat, which is now \"my seat\".", routed : false },
		{ b : "return", t : "on the way back {name} noticed a bruise and could not place it. it has been filed under \"adventure\".", routed : false },
		{ b : "return", t : "{planet} is getting smaller in the window. {name} is waving. this is a thing {name} does now.", routed : false },
		{ b : "return", t : "heading home with the haul. {name} keeps checking the bag is still a bag.", routed : false },
		{ b : "return", t : "heading home early. {name} is calling it a scouting trip and would like everyone else to as well.", w : 3, routed : true },
		{ b : "return", t : "the way back is shorter when you are running. {name} has tested this thoroughly.", w : 3, routed : true },
		{ b : "return", t : "leaving {planet} in a hurry. {name} would like to make clear that the planet started it.", w : 3, routed : true },
		{ b : "home", t : "home. {name} smells like {planet} and has decided that is a personality now.", routed : false },
		{ b : "home", t : "back. {name} told the story once, accurately, by accident. the next tellings have been corrected.", routed : false },
		{ b : "home", t : "home. the first thing {name} did was sit down. the second thing was also that.", routed : false },
		{ b : "home", t : "{name} is back and has been asked \"how was it\". the answer, \"big\", has been accepted.", routed : false },
		{ b : "home", t : "home. {name} has put the finds in a pile and is looking at the pile. it is a good pile.", routed : false },
		{ b : "home", t : "back from {planet}. {name} has one new scar and three new opinions about rocks.", routed : false },
		{ b : "home", t : "home. {name} slept for a long time and woke up still tired, which is how you know it was a real trip.", routed : false },
		{ b : "home", t : "landed home. {name} kissed the ground, then wiped the ground off, then wiped that off.", routed : false },
		{ b : "home", t : "home, limping. {name} has decided the limp is a souvenir.", w : 3, routed : true },
		{ b : "home", t : "back early. nobody asked. {name} told them anyway.", w : 3, routed : true },
		{ b : "home", t : "home. {name} is not talking about {planet}. {name} has said \"i'm not talking about it\" eleven times.", w : 3, routed : true },
		{ b : "sky", t : "the sky did nothing again today. {name} assumes this is a test and is passing it by also doing nothing." },
		{ b : "sky", t : "{name} looked up and said thanks, to be safe. nothing answered. that is usually what nothing does." },
		{ b : "sky", t : "{name} felt watched today, in a good way, like a plant on a windowsill." },
		{ b : "sky", t : "{name} asked the sky for a sign. a light blinked. it was the ship's. {name} has decided that was not the sign, and is waiting for a nicer one." },
		{ b : "sky", t : "dear whoever is up there: the snacks are fine. no complaints. small complaint about the cold. fine." },
		{ b : "sky", t : "{name} thanked the sky for a smooth crossing. the crossing is not smooth. {name} is being polite in advance." },
		{ b : "travel", t : "{name} and {partner} walked in silence for an hour. {name} thinks it went well.", party : 2, bond : 1 },
		{ b : "rest", t : "{partner} said something. {name} said \"yes\". it was not a yes question. they have agreed to move on.", party : 2, bond : 1 },
		{ b : "trap", t : "{partner} tripped. {name} laughed, then tripped in solidarity, then just tripped.", party : 2, bond : 2 },
		{ b : "find", t : "{name} and {partner} have a system. {name} points at things and {partner} says \"no\". it is working.", party : 2, bond : 2 },
		{ b : "rest", t : "{name} and {partner} shared the last ration by both pretending not to be hungry until it went off.", party : 2, bond : 3 },
		{ b : "travel", t : "{partner} knew what {name} was going to say and said it first. {name} said it anyway. twice.", party : 2, bond : 3 },
		{ b : "fight_open", t : "{foe} blocks the way. {name} looked at {partner}. {partner} looked at {name}. {foe} looked at both, and won that part.", party : 2 },
		{ b : "fight_won", t : "{foe} is down. {name} and {partner} are each telling it as a solo victory. the diary is staying out of it.", party : 2 },
		{ b : "fight_lost", t : "{name} and {partner} ran in different directions, then the same direction, then home.", party : 2 },
		{ b : "rest", t : "a quiet room. {partner} snored. {name} snored back. an accord was reached.", party : 2 },
		// ======================= THE VOICE PASS (2026-09-15): the road, the sky, the places, the quests =======================
		// ---- road: an hour of nothing ----
		{ b : "road", t : "an hour of road. {name} has reviewed it and found it to be road." },
		{ b : "road", t : "the road bends. {name} bent with it. they are both fine." },
		{ b : "road", t : "{name} counted steps for a while, then let the steps count themselves." },
		{ b : "road", t : "a milestone with no number. {name} gave it one. it is a nine now." },
		{ b : "road", t : "the road went up. then it went down. {name} feels this was a decision someone could have skipped." },
		{ b : "road", t : "{name} walked in the middle of the road, in case the sides were spoken for." },
		{ b : "road", t : "a puddle. {name} went around it, then back, then through it, to be sure." },
		{ b : "road", t : "{name} has been thinking about {place} for an hour and is no closer to it than the road allows." },
		{ b : "road", t : "the road is a paler dark than the rest. {name} is following the paler dark and hoping it knows.", night : true, w : 2 },
		{ b : "road", t : "an hour in the dark. {name} counted eyes in the hedge. two. probably the same animal. probably.", night : true, w : 2 },
		{ b : "road", t : "wet road. {name}'s boots have opinions and are sharing them with every step.", wx : "rain", w : 2 },
		{ b : "road", t : "fog. {name} walked toward {place} on the grounds that {place} is probably still where it was.", wx : "fog", w : 2 },
		{ b : "road", t : "an hour of road. {name} would like it noted that the road could have been shorter and chose not to be.", pers : "grumpy" },
		{ b : "road", t : "{name} waved at the road ahead. it is coming. it is being very patient.", pers : "cheerful" },
		{ b : "road", t : "{name} stopped to look at a beetle. the beetle was also going to {place}. they parted as equals.", pers : "curious" },
		{ b : "road", t : "{name} walked an hour with both eyes shut and only hit two things.", pers : "sleepy" },
		{ b : "road", t : "{name} and {partner} have not spoken for an hour. it is not a silence. it is a long pause.", party : 2, bond : 1 },
		{ b : "road", t : "{name} and {partner} played a game where you name a thing and the other says \"seen it\". {partner} has seen everything.", party : 2, bond : 3 },
		{ b : "road", t : "{name} tried to make the road shorter with a spell. the road is the same length and now a little warm.", cls : "mage" },
		{ b : "road", t : "{name} carried the pack the whole hour and has made sure everyone knows the pack is heavy.", cls : "warrior" },
		{ b : "road", t : "{name} walked the hour at the back, quietly, so as to be the surprise if anything happened. nothing happened. {name} was the surprise anyway.", cls : "rogue" },
		{ b : "road", t : "{partner} is grumbling. {name} has started grumbling along, in harmony, to keep {partner} company.", party : 2, ppers : "grumpy" },
		{ b : "road", t : "{partner} is asleep. walking. {name} is steering by the shoulder and it is going well.", party : 2, ppers : "sleepy" },
		// ---- night / dawn ----
		{ b : "night", t : "night. the road is still there, {name} checks, every few steps, with a foot." },
		{ b : "night", t : "dark. {name} has stopped looking at things and started listening at them." },
		{ b : "night", t : "night fell on {name} specifically, {name} feels." },
		{ b : "night", t : "the lamp is lit. it lights the lamp very well and not much else." },
		{ b : "night", t : "night on {planet}. the stars are in the wrong places and {name} has not corrected them yet." },
		{ b : "night", t : "{name} is not afraid of the dark. {name} is afraid of what the dark is doing. it is doing nothing. so far." },
		{ b : "night", t : "night. {name} likes it. nobody can see {name} liking it.", pers : "shy" },
		{ b : "night", t : "night. {name} suggested walking faster to get through it sooner. the night did not speed up.", pers : "eager" },
		{ b : "night", t : "{partner} took the lamp. {name} took the side nearest the hedge. they are both wrong about which is safer.", party : 2 },
		{ b : "night", t : "{name} has taken charge of the lamp. this is a responsibility and {name} is taking it seriously and slightly too high.", opens : "lamp", w : 2 },
		{ b : "night", t : "night in the marsh. everything that was wet is now also dark.", kind : "marsh", w : 2 },
		{ b : "night", t : "night in the desert. it went from too hot to too cold without passing through fine.", kind : "desert", w : 2 },
		{ b : "dawn", t : "dawn. everything is grey, then gold, then just there." },
		{ b : "dawn", t : "morning. {name} has counted everyone. everyone is here. the count was one, in some cases." },
		{ b : "dawn", t : "the sun came up behind {name}, which {name} takes as it being polite." },
		{ b : "dawn", t : "dawn on {planet}. the birds started and did not stop, which is a lot of confidence for birds." },
		{ b : "dawn", t : "light. {name} can see the road now and it is exactly where {name} had been standing." },
		{ b : "dawn", t : "the lamp went out at dawn, exactly when it stopped mattering. {name} is calling that timing.", closes : "lamp" },
		{ b : "dawn", t : "dawn. {name} was told. {name} will look at it later.", pers : "sleepy" },
		{ b : "dawn", t : "sunrise. {name} said good morning to it. it is now morning, so it worked.", pers : "cheerful" },
		// ---- weather ----
		{ b : "weather", t : "rain. {name} has put a hood up. the hood is a hand. the hand is also wet.", wx : "rain" },
		{ b : "weather", t : "it rains on {name} and it rains on {place} and the diary would like to note that it was {name}'s idea to come.", wx : "rain" },
		{ b : "weather", t : "rain. {name} said \"it will pass\". it has not passed. {name} is now saying it more quietly.", wx : "rain" },
		{ b : "weather", t : "snow. {name} caught one and it was gone before it could be examined. rude.", wx : "snow" },
		{ b : "weather", t : "snow on {planet}. {name} made a snow {name}. it is better at standing still.", wx : "snow" },
		{ b : "weather", t : "fog. {name} said hello to a post. the post was {partner}. {partner} said hello back.", wx : "fog", party : 2, w : 2 },
		{ b : "weather", t : "fog. {name} can see about a {name}'s length ahead. so, one {name}.", wx : "fog" },
		{ b : "weather", t : "wind. {name} leaned into it, and it stopped, and {name} leaned into the ground.", wx : "wind" },
		{ b : "weather", t : "wind in the face. {name} has turned around and is walking backwards for a bit, which is progress if you don't look.", wx : "wind" },
		{ b : "weather", t : "thunder. {name} counted the seconds and got a number that means \"close\".", wx : "storm" },
		{ b : "weather", t : "a storm. {name} is under a tree, which is what you are told not to do, and also what the tree is for.", wx : "storm" },
		{ b : "weather", t : "the sky cleared. {name} took it personally, in a good way.", wx : "clear" },
		{ b : "weather", t : "sun. {name} has forgiven the weather, provisionally.", wx : "clear" },
		{ b : "weather", t : "the weather changed. {name} noticed, and said so, and was told, and said so again." },
		// ---- inn / poor ----
		{ b : "inn", t : "an inn. a bed. {name} lay on it and made a noise that meant \"yes\"." },
		{ b : "inn", t : "the inn at {place}. the stew was a colour and a temperature and that was enough." },
		{ b : "inn", t : "{name} paid for the room, then checked under the bed for a cheaper room. there was a boot." },
		{ b : "inn", t : "a bed. {name} slept in it like a person who has slept in a ditch, because {name} has." },
		{ b : "inn", t : "the innkeeper asked where they were headed. {name} said \"away\". the innkeeper charged extra for that." },
		{ b : "inn", t : "an inn. {name} counted the coins twice before handing them over, once after, and once in the night from memory.", pers : "greedy" },
		{ b : "inn", t : "the inn at {place}. the bed was fine, the pillow was fine, {name} has complained about both.", pers : "grumpy" },
		{ b : "inn", t : "{name} got the good room by asking for the good room. everyone could have done that. nobody else did.", pers : "smug" },
		{ b : "inn", t : "one room, two beds. {name} and {partner} argued about the window and both slept with it open.", party : 2, bond : 3 },
		{ b : "inn", t : "one room, two beds. {name} and {partner} said goodnight at the same time and then lay very still.", party : 2, bond : 1 },
		{ b : "inn", t : "an inn, in the rain. {name} stood in the door a while, dripping, to make the point.", wx : "rain", w : 2 },
		{ b : "poor", t : "no coin. a barn. the hay is fine. the hay is honest." },
		{ b : "poor", t : "a barn at {place}. {name} slept beside something that breathed. it was a cow. it was probably a cow." },
		{ b : "poor", t : "the pocket is empty. {name} turned it out to be sure. a button. the button is not currency, {name} checked." },
		{ b : "poor", t : "no bed tonight. {name} has arranged the bag into a pillow and the disappointment into a blanket." },
		{ b : "poor", t : "no coin. {name} is taking this harder than the others and would like a moment.", pers : "greedy" },
		{ b : "poor", t : "a barn. {name} loves a barn. this was decided just now and is being maintained.", pers : "cheerful" },
		// ---- tavern / shop / bought ----
		{ b : "tavern", t : "the tavern at {place}. {name} sat at the bar and was served a look." },
		{ b : "tavern", t : "a tavern. someone was singing. {name} joined in on the wrong song." },
		{ b : "tavern", t : "{name} listened to the tavern for an hour and now knows everything about everyone in {place} except their names." },
		{ b : "tavern", t : "the tavern. {name} ordered the usual. {name} has never been here. they brought something anyway." },
		{ b : "tavern", t : "a bard. {name} asked for a song about {name}. there is not one yet. the bard is taking notes." },
		{ b : "tavern", t : "the tavern. {name} sat in the corner. the corner was already taken. {name} sat in the corner of the corner.", pers : "shy" },
		{ b : "tavern", t : "{name} challenged the tavern to an arm wrestle. the tavern, collectively, declined.", pers : "eager" },
		{ b : "tavern", t : "a rumour in the tavern about {goal}: something in the ground that hums. {name} has decided to believe it, to have something to look forward to.", opens : "rumour", w : 2 },
		{ b : "tavern", t : "{name} and {partner} sat at a table with three chairs and took turns being the third.", party : 2 },
		{ b : "tavern", t : "the tavern. {name} bought nobody a drink and would like credit for the restraint.", pers : "greedy" },
		{ b : "shop", t : "the shops at {place}. {name} looked at everything and touched most of it and bought the least of it." },
		{ b : "shop", t : "a shop. {name} asked the price of a thing, heard it, and left the thing where it was, along with {name}'s dignity." },
		{ b : "shop", t : "{name} haggled. the shopkeeper agreed to the first price. {name} is counting that as a win for both." },
		{ b : "shop", t : "the market at {place}. everything was for sale and nothing was for {name}." },
		{ b : "shop", t : "the shops. {name} went in with a plan and a purse and came out with the purse.", pers : "greedy" },
		{ b : "shop", t : "{name} asked the shopkeeper what a thing was for. the shopkeeper did not know either. {name} respects that.", pers : "curious" },
		{ b : "shop", t : "shops. {name} does not like shops. {name} went in anyway, to not like them from closer.", pers : "grumpy" },
		{ b : "shop", t : "the shops at {place}. {name} has no coin and looked at everything twice as long, to get the value.", poor : true, w : 3 },
		{ b : "bought", t : "{name} bought {item}. it is not clear what for. it is clear that it is {name}'s now." },
		{ b : "bought", t : "{name} bought {item} and has held it the whole way since, in case it is the kind that runs off." },
		{ b : "bought", t : "{name} bought {item}. the shopkeeper said it was the last one. there was a shelf of them. {name} has chosen not to notice." },
		{ b : "bought", t : "{name} bought {item} and would like it known that {name} spotted it first, before the shop did.", pers : "smug" },
		{ b : "bought", t : "{name} bought {item} and has already worked out what it will sell for. more. it will sell for more.", pers : "greedy" },
		{ b : "bought", t : "{name} bought {item}. {partner} asked why. {name} is still thinking of the answer and will have it by {goal}.", party : 2 },
		// ---- shrine / mine / ruin ----
		{ b : "shrine", t : "a shrine. {name} left a pebble on it. the shrine has a lot of pebbles. it is a popular shrine." },
		{ b : "shrine", t : "the shrine at {place}. {name} asked for something small. the shrine gave a feeling. a small one." },
		{ b : "shrine", t : "{name} lit a candle at the shrine and then had to explain to the others that it was not a birthday." },
		{ b : "shrine", t : "a shrine. {name} said a word to it. the word was \"hello\". the shrine is warm in the way stone is, which is not." },
		{ b : "shrine", t : "a shrine. {name} knew what to do at it, and did it, and the others watched like it was a trick.", cls : "cleric", w : 2 },
		{ b : "shrine", t : "the shrine hummed at {name}. {name} hummed back, in a key {name} is fairly sure is a spell.", cls : "mage" },
		{ b : "shrine", t : "a shrine. {name} bowed, briefly, to have it over with.", pers : "grumpy" },
		{ b : "shrine", t : "{name} took a candle from the shrine. borrowed. it will be returned. this will be a thing.", opens : "candle", w : 2 },
		{ b : "mine", t : "the mine at {place}. dark and wet and going down, which is all a mine promises." },
		{ b : "mine", t : "{name} filled a sack with something shiny and something less shiny and one thing that was a bug." },
		{ b : "mine", t : "the mine. {name} tapped the wall. the wall tapped back, later, from further away. moving on." },
		{ b : "mine", t : "ore. {name} does not know what it does, only that it is heavy, which is most of what ore does." },
		{ b : "mine", t : "{name} swung at the rock for an hour. the rock is a little smaller. {name} is a little larger, in the arms.", cls : "warrior" },
		{ b : "mine", t : "the mine has no light of its own and {name} has none to lend it. things were felt for.", haz : "dark", w : 2 },
		{ b : "mine", t : "a mine. {name} has kept a bit of ore back for {name}. it is a small bit. it is {name}'s bit.", pers : "greedy" },
		{ b : "ruin", t : "a ruin. someone's floor. {name} stood on it respectfully, then less so, then sat." },
		{ b : "ruin", t : "the ruin at {place}. a door with no house. {name} went through it properly, to be safe." },
		{ b : "ruin", t : "old stones. {name} put a hand on one. it was cold. the hand is now also cold. knowledge." },
		{ b : "ruin", t : "{name} found writing on a wall at the ruin. it said something in a language that has left. {name} said it back, badly." },
		{ b : "ruin", t : "{name} would like to stay at the ruin for a week. {name} has been given a minute.", pers : "curious" },
		{ b : "ruin", t : "a ruin. {name} checked it for anything left behind. a lot was left behind. all of it was wall.", pers : "greedy" },
		// ---- wild: the land itself ----
		{ b : "wild", t : "a field. {name} walked across it, which is what a field is for, and the field agreed.", kind : "field" },
		{ b : "wild", t : "the forest at {place}. trees, mostly, and the space between them, which {name} kept to.", kind : "forest" },
		{ b : "wild", t : "{name} hugged a tree. it was an accident. the tree took it well.", kind : "forest" },
		{ b : "wild", t : "the marsh. {name} lost a boot to it, and got it back, and lost it again to the same spot. the spot is keeping it.", kind : "marsh" },
		{ b : "wild", t : "marsh. everything squelches, including, by the end, {name}'s opinions.", kind : "marsh" },
		{ b : "wild", t : "the desert at {place}. sand in every direction and in {name}.", kind : "desert" },
		{ b : "wild", t : "hot. {name} tried walking in the shade. there is no shade. {name} is now the shade, for a beetle.", kind : "desert" },
		{ b : "wild", t : "hills. up, then a view, then down, then the view was behind them. {name} is not sure the view was worth the up.", kind : "hills" },
		{ b : "wild", t : "mountains. {name} looked up at the top and the top looked down and neither of them has moved.", kind : "mountains" },
		{ b : "wild", t : "the coast. {name} put a foot in the sea. the sea put itself in the boot. an exchange.", kind : "coast" },
		{ b : "wild", t : "tundra. flat and white and quiet in a way that feels like it is waiting for {name} to say something.", kind : "tundra" },
		{ b : "wild", t : "an island. {name} walked around it, which took a while, and ended up where {name} started, which was the plan.", kind : "isle" },
		{ b : "wild", t : "the wild at {place}. nothing happened. {name} watched it not happen with great attention." },
		{ b : "wild", t : "{name} knows this kind of country and has said so, and then walked into a bog to prove the country did not know {name}.", cls : "ranger" },
		// ---- camp / delve / hazard ----
		{ b : "camp", t : "a bandit camp. tents, a fire, a pot of something. {name} went in the way you go into a cold bath: all at once and regretting it midway." },
		{ b : "camp", t : "the camp at {place}. {name} counted the bandits, then the tents, then decided counting was not the skill for today." },
		{ b : "camp", t : "bandits. {name} announced the crew's arrival, which was not the plan, but is now the situation." },
		{ b : "camp", t : "a camp. {name} was inside it before the others had finished the word \"camp\".", pers : "eager" },
		{ b : "camp", t : "the bandit camp. {name} would have liked to knock.", pers : "shy" },
		{ b : "camp", t : "the camp at {place}. {name} went in from the side the bandits were not looking at, which was, briefly, all of the sides.", cls : "rogue" },
		{ b : "delve", t : "into {place}. it is dark, and going down, and {name} has led the way by being in front by accident." },
		{ b : "delve", t : "{place}. the door was open, which is either welcoming or the other thing." },
		{ b : "delve", t : "down into {place}. {name} is counting the steps, to know how far the running back is." },
		{ b : "delve", t : "the crypt at {place}. cold, and quiet, and full of people who are not going anywhere. {name} has kept the voice down.", kind : "crypt", w : 2 },
		{ b : "delve", t : "a crypt. {name} said \"sorry\" to the first coffin and stopped after the fifth. it was taking too long.", kind : "crypt", w : 2 },
		{ b : "delve", t : "it is dark in {place} and {name} is finding the walls the traditional way, with the face.", haz : "dark", w : 2 },
		{ b : "delve", t : "{place}. {name} touched the first thing inside the door. it was a wall. {name} is pleased to have learned what the wall is.", pers : "curious" },
		{ b : "delve", t : "the humming thing from the rumour is real. it is the wind in a pipe. {name} is counting it.", closes : "rumour" },
		{ b : "delve", t : "into {place}. {name} lit the way and has been told to point the light at the floor, and then at the wall, and then at nothing, by everyone in turn.", cls : "mage" },
		{ b : "hazard", t : "the dark. {name} cannot see the foe and the foe, {name} hopes, cannot see {name}. one of them is wrong.", haz : "dark" },
		{ b : "hazard", t : "dark. {name} is swinging at where things sound like they are.", haz : "dark" },
		{ b : "hazard", t : "the damp. {name}'s spell fizzled like a wet match, which is what it was, in a sense.", haz : "damp" },
		{ b : "hazard", t : "everything is wet, including the magic. {name} has tried drying it on a sleeve.", haz : "damp" },
		{ b : "hazard", t : "the heat. {name} moved at a speed the foe found generous.", haz : "heat" },
		{ b : "hazard", t : "hot. every swing is a decision, and {name} is taking a long time over each.", haz : "heat" },
		{ b : "hazard", t : "cold hands. {name} can hold the weapon or feel it, not both.", haz : "cold" },
		{ b : "hazard", t : "the cold has {name}'s fingers. {name} is asking for them back.", haz : "cold" },
		// ---- meet / fetch / found / deliver ----
		{ b : "meet", t : "met {who} at {place}. {who} has a cart, a mule, and a great deal to say about both." },
		{ b : "meet", t : "{who} was ready to go and has been for some time, {who} says, and says again." },
		{ b : "meet", t : "{who}'s cart is loaded. {name} asked with what. {who} said \"goods\", like a door closing." },
		{ b : "meet", t : "{who}. the mule is called something. {name} did not catch it and has been calling it \"the mule\", which the mule accepts." },
		{ b : "meet", t : "{name} has asked the mule's name. the mule's name is long. {name} is working on it.", opens : "mule", w : 2 },
		{ b : "meet", t : "{who}'s cart. {name} checked the goods for value and found the goods to be closed.", pers : "greedy" },
		{ b : "meet", t : "{who} walks between {name} and {partner}, talking to both, listening to neither. this is how a merchant walks.", party : 2 },
		{ b : "fetch", t : "found {who}. it was where it was left, which is more than can be said for most things." },
		{ b : "fetch", t : "{who}. {name} picked it up and it is heavier than the word for it." },
		{ b : "fetch", t : "found {who} under a rock. everything is under a rock. {name} has begun to distrust rocks." },
		{ b : "fetch", t : "{who}, retrieved. {name} is carrying it in both arms like it is asleep." },
		{ b : "fetch", t : "found {who}. {name} would like to know what it does and has been told not to find out.", pers : "curious" },
		{ b : "fetch", t : "found {who}. {name} sat down next to it for a bit first. it was not going anywhere. neither was {name}.", pers : "sleepy" },
		{ b : "found", t : "found {who}. {who} was fine, {who} says, and had it under control, {who} says, from under the table." },
		{ b : "found", t : "{who} was in the last place they looked, which {name} feels is how it always goes, and is right." },
		{ b : "found", t : "{who}, found. {who} asked what took so long. {name} gave a look that took longer." },
		{ b : "found", t : "found {who} asleep. {name} woke {who} gently, then less gently, then with a boot." },
		{ b : "found", t : "{name} found {who}. {partner} found {name} finding {who}. both are taking credit and the diary is letting them.", party : 2 },
		{ b : "found", t : "found {who}. {name} said \"there you are\", as if {who} had been the one looking.", pers : "smug" },
		{ b : "deliver", t : "delivered. {who} is where {who} was meant to be, and so is {name}, briefly, before the walk back." },
		{ b : "deliver", t : "handed over at {place}. there was a receipt. {name} kept it. it is the first receipt {name} has ever kept." },
		{ b : "deliver", t : "done. {who} said thank you in the way people say it when they mean \"finally\"." },
		{ b : "deliver", t : "delivered to {place}. {name} stood there for a moment waiting for more to happen. it did not. that was the job." },
		{ b : "deliver", t : "delivered. {name} would like it recorded that it went perfectly, and it is recorded, and there is a small bruise not mentioned.", pers : "smug" },
		{ b : "deliver", t : "delivered. {name} hugged {who}. {who} was not ready. {who} is now.", pers : "cheerful" },
		{ b : "deliver", t : "delivered. the mule's name, it turns out, was \"mule\". {name} feels this could have been said sooner.", closes : "mule" },
		{ b : "deliver", t : "delivered. {name} counted the payment in front of {who}, slowly, which is either rude or careful, and {name} is going with careful.", pers : "greedy" },
		// ---- boss / wave / chart ----
		{ b : "boss", t : "{foe}. it has a name and a title and the title is earned. {name} has neither and is going in anyway." },
		{ b : "boss", t : "{foe} stood up. it kept standing up. there was more of it than the standing suggested." },
		{ b : "boss", t : "{foe}. {name} said its name, to be polite, and it did not like being known." },
		{ b : "boss", t : "the bounty. {foe}, in person, larger than the poster and angrier than the price." },
		{ b : "boss", t : "{foe}. {name} has been looking forward to this and has said so, to {foe}, which was a tactical error.", pers : "smug" },
		{ b : "boss", t : "{foe}. {name} would like to go home now and has said so, quietly, to the wall.", pers : "shy" },
		{ b : "boss", t : "{foe}. {name} and {partner} agreed to go in together and went in one at a time anyway.", party : 2 },
		{ b : "boss", t : "{foe}. {name} has fought bigger, {name} says. {name} is level two. the bigger thing was a goose.", lv : "low" },
		{ b : "wave", t : "a wave of them, over the fence. {name} has picked a spot and is standing on it as if the spot matters." },
		{ b : "wave", t : "here they come. the villagers are indoors. {name} can hear them being indoors." },
		{ b : "wave", t : "another wave. {name} counted them out loud, which helped nobody and continued anyway." },
		{ b : "wave", t : "the village fence is not much of a fence. {name} is the fence now." },
		{ b : "wave", t : "a wave. {name} met it halfway, which is further than halfway, which is the problem with {name}.", pers : "eager" },
		{ b : "wave", t : "another wave. {name} has asked how many waves there are and been told a number and is disputing it.", pers : "grumpy" },
		{ b : "wave", t : "a wave. {name} put {partner} on the left and took the right, and they have both ended up in the middle.", party : 2 },
		{ b : "wave", t : "here they come. {name} has healed everyone in advance, which is not how it works, and has been told, and has done it again.", cls : "cleric" },
		{ b : "chart", t : "charted {place}. {name} drew it. it is a circle with a name in. it is a good circle." },
		{ b : "chart", t : "{place}, on the map now, roughly where it is." },
		{ b : "chart", t : "{name} charted {place} by standing in it and looking around, which is the whole of cartography." },
		{ b : "chart", t : "another place on the chart. {name} has started drawing small animals in the corners. the corners are filling up." },
		{ b : "chart", t : "charted {place}. {name} has added notes. the notes are longer than the map.", pers : "curious" },
		{ b : "chart", t : "charted {place}. {partner} held the paper. {name} held the pen. the paper moved. this is {partner}'s map now, {name} says.", party : 2 },
		// ---- lost ----
		{ b : "lost", t : "lost. {name} says not lost. the road says nothing. the road was never asked." },
		{ b : "lost", t : "the wrong road. {name} noticed when it started going somewhere else, and followed it a while, to be sure." },
		{ b : "lost", t : "an hour in a circle. the same tree twice, then a third time, at which point {name} and the tree agreed to stop meeting." },
		{ b : "lost", t : "{name} knew the way. {name} knew a way. it was not this one." },
		{ b : "lost", t : "the wrong road in the dark, and the right one found by walking until it was the one there was." },
		{ b : "lost", t : "{name} was not lost. {name} was exploring the wrong road on purpose, for the diary.", pers : "smug" },
		{ b : "lost", t : "lost. {name} blamed the map. there is no map. {name} blamed the lack of map.", pers : "grumpy" },
		{ b : "lost", t : "{name} and {partner} disagreed about the road and were both wrong, in the same direction, which is called teamwork.", party : 2 },
		{ b : "lost", t : "the map was of somewhere else. {name} has folded it to be the right way up, which has not helped.", closes : "map" },
		{ b : "lost", t : "lost in the fog. {name} is following the sound of {partner}, who is following the sound of {name}.", wx : "fog", party : 2, w : 2 },
		{ b : "lost", t : "lost. {name} knows this country, {name} said, and the country has not returned the favour.", cls : "ranger" },
		{ b : "land", t : "{name} bought a map at the landing. it is a good map of somewhere.", opens : "map", w : 2 },
		// ---- levelup / skill ----
		{ b : "levelup", t : "{name} is a level stronger and has checked, by lifting a thing. the thing was liftable before. it is more liftable now." },
		{ b : "levelup", t : "a level. {name} feels taller. {name} is not taller. the feeling is the level." },
		{ b : "levelup", t : "{name} has gone up a level and has told the others and is now telling the diary and will tell the ship." },
		{ b : "levelup", t : "level up. {name} did nothing different and would like the same nothing tomorrow." },
		{ b : "levelup", t : "a level. {name} has been expecting it and is pretending to be surprised, for the others.", pers : "smug" },
		{ b : "levelup", t : "{name} levelled up and lay down, in case it wore off.", pers : "sleepy" },
		{ b : "levelup", t : "a level. {name} asked for the next one now. it does not work like that. {name} is asking anyway.", pers : "eager" },
		{ b : "levelup", t : "a level. {name}'s spells have a little more in them, {name} says, and says it with a little more in the voice, too.", cls : "mage" },
		{ b : "levelup", t : "a level. {name} has hit a tree to check. the tree has agreed.", cls : "warrior" },
		{ b : "levelup", t : "a level. {name} has decided it was the shrine. it was the goblins. {name} is thanking the shrine anyway.", cls : "cleric" },
		{ b : "levelup", t : "level up. {name} said nothing, and stood a little straighter, and was noticed, and went red.", pers : "shy" },
		{ b : "levelup", t : "a level. {partner} clapped. once. {name} is keeping the clap.", party : 2 },
		{ b : "levelup", t : "a big level. {name} has been at this a while and it shows, in the walk, and in the way {name} no longer counts the goblins first.", lv : "high", w : 2 },
		{ b : "skill", t : "{name} has a new trick and has done it at nothing, twice, to make sure it stays." },
		{ b : "skill", t : "a new skill. {name} is not sure where it came from and has decided not to ask, in case it goes back." },
		{ b : "skill", t : "{name} learned a thing today and immediately forgot how, which is how the good ones work." },
		{ b : "skill", t : "{name} has a new trick and has taken it apart to see how it works and is now putting it back.", pers : "curious" },
		{ b : "skill", t : "a new trick. {name} showed {partner}. {partner} said \"again\". {name} could not do it again. it will come back.", party : 2 },
		{ b : "skill", t : "a new spell. {name} has named it. the name is longer than the spell.", cls : "mage" },
		// ---- home, by the quest's kind ----
		{ b : "home", t : "home. {name} misses the mule. this was not expected and is not being discussed.", qk : "escort", w : 3, routed : false },
		{ b : "home", t : "home. {name} has still not got the mule's name and has stopped asking, out loud.", closes : "mule" },
		{ b : "home", t : "home. {who} was delivered. {name} keeps looking for it, out of habit.", qk : "fetch", w : 3, routed : false },
		{ b : "home", t : "home. {who} waved from {goal} for a long time, {name} imagines. {name} did not look back, to keep it that way.", qk : "rescue", w : 3, routed : false },
		{ b : "home", t : "home. the bounty is paid. {name} has kept the poster and would like it framed.", qk : "bounty", w : 3, routed : false },
		{ b : "home", t : "home with the chart. it has been looked at by everyone and understood by {name}, mostly.", qk : "survey", w : 3, routed : false },
		{ b : "home", t : "home. the sacks are heavy and so is {name}, in a good way.", qk : "gather", w : 3, routed : false },
		{ b : "home", t : "home. {goal} still stands, as far as {name} knows, and {name} intends to keep not knowing.", qk : "defend", w : 3, routed : false },
		{ b : "home", t : "the shrine's candle made it home. it has not been returned. {name} is calling it a long borrow.", closes : "candle" },
		{ b : "home", t : "the rumour about the humming thing has been passed on, at home, with improvements.", closes : "rumour" },
		{ b : "home", t : "the map has been kept. it will be right somewhere.", closes : "map" },
		{ b : "home", t : "home, and the pocket is empty, and {name} has explained to it that this is temporary.", poor : true, w : 2, routed : false },
		{ b : "home", t : "home from the marsh. {name} will be drying for a week and has begun.", qk : "explore", kind : "marsh", w : 2 },
		// ---- a few more for the old beats, gated new ways ----
		{ b : "fight_open", t : "{foe}, in the rain. {name} is wet, {foe} is wet, and only one of them minds.", wx : "rain", w : 2 },
		{ b : "fight_open", t : "{foe}, in the dark. {name} heard it before seeing it and would have preferred neither.", night : true, w : 2 },
		{ b : "fight_open", t : "{foe}. {name} has a spell for this. {name} has a spell for most things and they are all the same spell.", cls : "mage" },
		{ b : "fight_open", t : "{foe}. {name} said a small prayer, mostly for {foe}, out of habit.", cls : "cleric" },
		{ b : "fight_open", t : "{foe}. {name} went round behind it, which is where {name} goes, and where {foe} was also looking.", cls : "rogue" },
		{ b : "fight_open", t : "{foe}. {name} has seen its tracks for an hour and is not surprised, and is a little pleased, and is keeping the pleased down.", cls : "ranger" },
		{ b : "fight_open", t : "{foe}. {name} has gone first, as usual, and has asked the others to come along at some point.", cls : "warrior" },
		{ b : "fight_won", t : "{foe} is down and {partner} is already telling it wrong. {name} is letting {partner}. it is a better version.", party : 2, bond : 3 },
		{ b : "fight_won", t : "won. {partner} did most of it. {name} did the last of it, which is the part that counts, {name} has decided.", party : 2, ppers : "smug" },
		{ b : "fight_won", t : "{foe} is down. {name} is whole, mostly, and has counted the parts and they are all there, roughly.", hp : "low", w : 2 },
		{ b : "fight_lost", t : "routed in the dark. {name} ran toward the lighter dark and is calling that navigation.", night : true, w : 2 },
		{ b : "fight_lost", t : "routed. {partner} went one way and {name} the other and they met again at the road, both claiming the other had panicked.", party : 2 },
		{ b : "rest", t : "rested. {name} is whole, and has checked twice, and is being careful with it, like a full cup.", hp : "full", w : 2 },
		{ b : "find", t : "found {item}, in the rain, which makes it a wet {item}, which {name} feels is a different and lesser thing.", wx : "rain", w : 2 },
		{ b : "find", t : "found {item}. {partner} says it is {partner}'s. {name} found it. they are sharing it, in the sense that {name} is carrying it.", party : 2, bond : 2 },
		// ======================= THE PERSONALITIES PASS (2026-09-15): brave / dreamy / nervous / proud / kind / sly =======================
		{ b : "depart", t : "{name} volunteered before the trip was described. it has been described. {name} is still in.", pers : "brave" },
		{ b : "fight_open", t : "{foe}. {name} went first, which is where {name} goes, and where the hitting is.", pers : "brave" },
		{ b : "road", t : "{name} walked in front all hour, to be the one that meets things. nothing met {name}. {name} is disappointed.", pers : "brave" },
		{ b : "depart", t : "{name} got on the ship, looked out of the window, and is still looking. the trip is a window now.", pers : "dreamy" },
		{ b : "rest", t : "{name} lay down to think and forgot the thought and kept the lie-down.", pers : "dreamy" },
		{ b : "road", t : "{name} walked into a tree while looking at a cloud. apologised to the cloud.", pers : "dreamy" },
		{ b : "fight_open", t : "{foe}. {name} said \"oh no\" eleven times and then, on the twelfth, hit it.", pers : "nervous" },
		{ b : "night", t : "night. {name} has counted the noises. there are more noises than things, {name} is sure.", pers : "nervous" },
		{ b : "land", t : "{name} stepped off the ship, stepped back on, and stepped off again to make it official.", pers : "nervous" },
		{ b : "fight_won", t : "{foe} is down. {name} did it, {name} says, and the diary is inclined to agree because {name} is standing closest.", pers : "proud" },
		{ b : "find", t : "found {item}. {name} found it, specifically, and would like the record to say who.", pers : "proud" },
		{ b : "levelup", t : "a level. {name} has been ready for it for some time and has said so, in advance, to everyone.", pers : "proud" },
		{ b : "rest", t : "{name} gave the good blanket to {partner} and slept in the coat. it was a good coat, {name} says.", pers : "kind", party : 2 },
		{ b : "fight_won", t : "{foe} is down. {name} checked it was not in pain. it is not in anything now.", pers : "kind" },
		{ b : "road", t : "{name} carried {partner}'s bag for an hour. {partner} did not notice. {name} did not mention it.", pers : "kind", party : 2 },
		{ b : "find", t : "found {item}. {name} found it a bit earlier than the others were told.", pers : "sly" },
		{ b : "shop", t : "{name} paid, mostly. the shopkeeper counted twice and {name} was already outside.", pers : "sly" },
		{ b : "tavern", t : "{name} won at cards. nobody saw how. {name} is not saying how.", pers : "sly" },
		// ======================= THE WORLD'S PROPERTIES (2026-09-15, take two): its moons, its ring =======================
		{ b : "land", t : "{planet} has a ring. {name} walked under it for an hour and it did not come down, which {name} is choosing to trust.", ringed : true, w : 3 },
		{ b : "night", t : "the ring is up. it goes from one side of the sky to the other and {name} has stopped checking that it does.", ringed : true, w : 3 },
		{ b : "sky", t : "{name} asked the ring what it was for. it is for looking at, apparently. {name} looked at it.", ringed : true, w : 3 },
		{ b : "land", t : "one moon, up in the day, faint, like it forgot to leave.", moons : 1, w : 2 },
		{ b : "night", t : "two moons. {name} has picked a favourite and is not saying which, in case the other one hears.", moons : 2, w : 3 },
		{ b : "dawn", t : "both moons set as the sun came up, one after the other, like a queue.", moons : 2, w : 3 },
		{ b : "night", t : "three moons. {name} has given up counting them and is counting the dark between, which is easier.", moons : 3, w : 3 },
		{ b : "night", t : "four moons. the night is not dark so much as busy. {name} has asked one of them to leave.", moons : 4, w : 3 },
		{ b : "night", t : "no moon. the dark is the whole dark. {name} has put a hand out in front and cannot report on it.", moonless : true, w : 3 },
		{ b : "lost", t : "no moon to go by. {name} went by feel, and the feel was wrong.", moonless : true, w : 3 },
	];
	return _l;
}
