/// @description exped_lines() -> THE DIARY's lines (his ask, 2026-09-12:
/// "lots of fun little lore bits... dumb funny... but with logic and
/// structure so there is consistency and continuity"). Every entry is a
/// TEMPLATE with GATES; exped_say picks one per beat and fills the slots.
///
/// THE SHAPE (the register: a dim, self-aware narrator, deadpan,
/// anticlimax, literal-minded, the world never reacts, no exclamation
/// marks, one joke a line, the truth line above it always says plainly
/// what happened):
///   b       the beat - depart / travel / land / find / rest / trap /
///           fight_open / fight_won / fight_lost / return / home / sky
///   t       the text; slots {name} {planet} {biome} {foe} {item} {partner}
///   pers    only this personality says it (sprite_personalities names)
///   biome   only on this world (exped_biomes names)
///   party   1 = only alone, 2 = only with a partner along
///   bond    with a partner: 1 strangers / 2 mates / 3 inseparable
///   hp      "low" = only under 40% hp
///   routed  only when the trip is / is not routed
///   opens   starts a THREAD on the trip (a setup); refused if already open
///   closes  needs that thread open, and closes it (the payoff) - closers
///           are preferred whenever one qualifies, and the trip's end
///           closes what is left. THIS is what makes it a diary rather
///           than a list of jokes: a line in room 2 that room 4 answers
///   need    a MEMORY gate (exped_say): "first" (the sprite's first trip),
///           "third" (third or later), "revisit" (this planet again),
///           "routed_before", "streak3" (three trips unrouted), "wins3",
///           "retired" (someone has been swapped out - {retired} names them)
///   w       weight (default 1) - the specific beats the generic
///
/// ⚖️ ORIGINAL LINES, in a register he liked from elsewhere. Add, cut,
/// retune here - the file IS the voice; a line that falls flat is one
/// line to delete.
function exped_lines() {
	static _l = [
		{ b : "depart", t : "{name} packed for every eventuality except the trip." },
		{ b : "depart", t : "{name} left a note for the others. it says \"gone\". it is very thorough." },
		{ b : "depart", t : "departure. {name} waved at the ship for a while before being told to get in it." },
		{ b : "depart", t : "{name} has a plan for {planet}. the plan is to arrive. beyond that, improvisation." },
		{ b : "depart", t : "{name} checked the supplies twice and the snacks nine times." },
		{ b : "depart", t : "the ship made a noise on the way out. {name} has decided it was a happy noise." },
		{ b : "depart", t : "{name} asked where {planet} was. up, apparently. {name} is heading up." },
		{ b : "depart", t : "last thing before leaving: {name} touched the doorframe for luck. the doorframe did not react. that is how luck works." },
		{ b : "depart", t : "{name} was in the ship before anyone said go. no one had said go. no one was going to.", pers : "eager" },
		{ b : "depart", t : "{name} boarded, sat down, and was asleep before the door closed. an efficient start.", pers : "sleepy" },
		{ b : "depart", t : "{name} has been to space before. once. in a dream. it counts.", pers : "smug" },
		{ b : "depart", t : "{name} pressed every button in the ship to learn what they did. two of them did something. the trip has begun regardless.", pers : "curious" },
		{ b : "depart", t : "{name} did not want to go. {name} went. this is the whole story of {name}.", pers : "grumpy" },
		{ b : "depart", t : "{name} named the ship on the way out. the ship is called \"the ship\". it suits her.", pers : "cheerful" },
		{ b : "depart", t : "{name} said goodbye to everyone very quietly, from inside the ship, after it had left.", pers : "shy" },
		{ b : "depart", t : "{name} has brought a bigger bag than the ship. the bag is folded. the plan is not.", pers : "greedy" },
		{ b : "depart", t : "{name}'s first expedition. everything is a first. the ship, the dark, the snacks tasting like the dark.", need : "first", w : 3 },
		{ b : "depart", t : "third time out. {name} has started packing the right things, which takes some of the fun out of it.", need : "third", w : 2 },
		{ b : "depart", t : "{name} has been routed before and has decided this time will be different, in ways that have not been specified.", need : "routed_before", w : 2 },
		{ b : "depart", t : "three trips without running away. {name} is not counting. {name} is counting.", need : "streak3", w : 2 },
		{ b : "travel", t : "day one of the crossing. {name} has named the stars. all of them greg." },
		{ b : "travel", t : "space is mostly nothing, and the nothing is very well organised." },
		{ b : "travel", t : "{name} tried to count the stars, lost count at eleven, and started again from \"many\"." },
		{ b : "travel", t : "the ship hums. {name} hums back. neither of them knows the tune." },
		{ b : "travel", t : "halfway. {name} celebrated by eating tomorrow's ration, then today's, in that order." },
		{ b : "travel", t : "{name} has been practising a landing face in the window. the window is not convinced." },
		{ b : "travel", t : "there was a moment of turbulence. {name} apologised to it." },
		{ b : "travel", t : "{name} watched a dot get slightly bigger for an hour. the dot is {planet}. the hour was worth it, probably." },
		{ b : "travel", t : "{name} slept through the interesting part of space. all of space is the interesting part. {name} slept through space.", pers : "sleepy" },
		{ b : "travel", t : "{name} asked the ship where it was going. the ship said nothing, which {name} took as \"you'll see\".", pers : "curious" },
		{ b : "travel", t : "the view is stars. it has been stars for hours. {name} has requested different stars.", pers : "grumpy" },
		{ b : "travel", t : "{name} spotted {planet} first. there was no one else to spot it. still counts.", pers : "smug" },
		{ b : "travel", t : "{name} has been talking to the snacks. the snacks are good listeners and getting fewer.", pers : "cheerful" },
		{ b : "travel", t : "{name} thought about {retired} today. {retired} would have hated this. {name} is hating it for both of them.", need : "retired", w : 2 },
		{ b : "rest", t : "a quiet room. {name} found a mark on the wall that looked like {retired}'s handwriting. it was a crack. {name} sat with it a while anyway.", need : "retired", w : 2 },
		{ b : "land", t : "{retired} always said {name} would end up somewhere like {planet}. {retired} meant it as a warning.", need : "retired", w : 2 },
		{ b : "home", t : "home. someone had used {retired}'s old spot. {name} has moved them, gently, and said nothing.", need : "retired", w : 2 },
		{ b : "land", t : "landed. the ground is here, as advertised." },
		{ b : "land", t : "{name} stepped out, breathed in, and coughed for a bit. the air is real, then." },
		{ b : "land", t : "first footprint on {planet}. {name} went back and made it deeper so it would last." },
		{ b : "land", t : "{planet} has weather. {name} is not sure which kind yet, but it is happening." },
		{ b : "land", t : "arrived. {name} has planted a flag. the flag is a stick. the stick is planted." },
		{ b : "land", t : "the landing was smooth if you don't count the landing." },
		{ b : "land", t : "landed on {planet}. it is a rock. {name} respects that.", biome : "stone", w : 2 },
		{ b : "land", t : "{planet} is grey in every direction. {name} has picked a direction and is calling it forward.", biome : "stone", w : 2 },
		{ b : "land", t : "the rocks here are big. {name} has decided not to compete.", biome : "stone", w : 2 },
		{ b : "land", t : "everything on {planet} is a rock, including, {name} suspects, the sky.", biome : "stone", w : 2 },
		{ b : "land", t : "the ground on {planet} breathes. {name} has decided not to mention this to the ground.", biome : "living", w : 2 },
		{ b : "land", t : "something on {planet} said hello. {name} said hello back. now they are both waiting.", biome : "living", w : 2 },
		{ b : "land", t : "the plants here lean toward {name}. {name} is trying to take it as a compliment.", biome : "living", w : 2 },
		{ b : "land", t : "{planet} smells like a greenhouse that has opinions.", biome : "living", w : 2 },
		{ b : "land", t : "ruins. someone built all this and then left, which {name} considers a very relatable decision.", biome : "ruined", w : 2 },
		{ b : "land", t : "there are doors on {planet} with nothing behind them. {name} knocked anyway. manners.", biome : "ruined", w : 2 },
		{ b : "land", t : "whoever lived on {planet} left in a hurry and took the roofs.", biome : "ruined", w : 2 },
		{ b : "land", t : "{name} found a statue with the face worn off. gave it a face. it looks surprised.", biome : "ruined", w : 2 },
		{ b : "land", t : "{planet} is cold in a way that feels personal.", biome : "ice", w : 2 },
		{ b : "land", t : "the snow on {planet} squeaks. {name} has apologised to it twice.", biome : "ice", w : 2 },
		{ b : "land", t : "{name} tried to make a snow version of {name}. it looked better. left it.", biome : "ice", w : 2 },
		{ b : "land", t : "everything on {planet} is frozen except {name}'s opinion of the cold, which is heating up.", biome : "ice", w : 2 },
		{ b : "land", t : "back on {planet}. the rocks recognise {name}. the feeling is not mutual.", need : "revisit", w : 4 },
		{ b : "find", t : "found {item}. {name} has no idea what it does and intends to keep it in a pocket until it becomes important." },
		{ b : "find", t : "found {item}. it was under a rock. most things are, if you are willing to lift enough rocks." },
		{ b : "find", t : "found {item}. {name} looked around for the owner, found no one, and became the owner." },
		{ b : "find", t : "found {item} and immediately dropped it, to check it wasn't a trick. it wasn't. picked it up again. still isn't." },
		{ b : "find", t : "found {item}. it was labelled \"do not take\". {name} does not read labels, which has turned out to be a skill." },
		{ b : "find", t : "found {item}. {name} did a small dance. there was no one to see it, which is the best kind of dance." },
		{ b : "find", t : "found {item}. {name} said \"aha\", quietly, in case it was a mistake." },
		{ b : "find", t : "found {item}, wedged in a crack. the crack is fine. the crack has been through worse." },
		{ b : "find", t : "found {item}. {name} has decided it is worth a lot, based on how hard it was to reach." },
		{ b : "find", t : "found {item} exactly where {name} would have hidden it. {name} is now suspicious of {name}." },
		{ b : "find", t : "found {item}. {name} has already spent it three times in {name}'s head.", pers : "greedy" },
		{ b : "find", t : "found {item}. {name} turned it over for a long time. it has two sides. noted.", pers : "curious" },
		{ b : "find", t : "found {item}. {name} said \"finally\" as if it had been promised.", pers : "grumpy" },
		{ b : "find", t : "found {item}. {name} knew it would be here. {name} did not know it would be here.", pers : "smug" },
		{ b : "find", t : "also: a small rock that seemed to be watching. bringing it along. for science, or company.", opens : "rock", w : 2 },
		{ b : "find", t : "there was a sound in the walls that {name} is choosing to call \"the neighbour\".", opens : "neighbour", w : 2 },
		{ b : "rest", t : "{name} picked up a stick. it is a good stick. this is going to be a whole thing.", opens : "stick", w : 2 },
		{ b : "land", t : "{name} has started a collection of interesting pebbles. it is one pebble. it is interesting.", opens : "pebble", w : 2 },
		{ b : "find", t : "the rock has been checked. it is a rock. {name} would appreciate this not being brought up.", closes : "rock" },
		{ b : "rest", t : "the rock fell out of a pocket. {name} went back for it. no one saw.", closes : "rock" },
		{ b : "home", t : "the rock made it home. it has a shelf now. it is still a rock, but a housed one.", closes : "rock" },
		{ b : "rest", t : "update on the neighbour: it was the wind. {name} has forgiven it.", closes : "neighbour" },
		{ b : "home", t : "the neighbour followed {name} to the ship. it is still the wind. it is coming home.", closes : "neighbour" },
		{ b : "trap", t : "the stick broke. {name} is carrying both halves out of respect.", closes : "stick" },
		{ b : "home", t : "the stick has been named. its name is stick. it prefers it.", closes : "stick" },
		{ b : "find", t : "the pebble collection is now two pebbles. the second one is a bit of the first one.", closes : "pebble" },
		{ b : "home", t : "the pebble collection did not survive the trip. it was one pebble. it is somewhere on {planet} now, being interesting alone.", closes : "pebble" },
		{ b : "rest", t : "a quiet room. {name} sat in it and thought about nothing so hard the nothing left." },
		{ b : "rest", t : "rested. {name} lay down for a minute and got up in a different mood, which is the whole point of minutes." },
		{ b : "rest", t : "a calm room. {name} took off both boots, then remembered {name} has no boots, then had a lie down about it." },
		{ b : "rest", t : "{name} found a corner with no drafts and would like to live there. moving on anyway. duty." },
		{ b : "rest", t : "rested here. the wall was warm. {name} has thanked the wall." },
		{ b : "rest", t : "a quiet room. {name} hummed. the room hummed back, a bit late, a bit lower. they left it there." },
		{ b : "rest", t : "sat down. counted the supplies. counted them again in case the first count was rude." },
		{ b : "rest", t : "{name} took a nap and dreamt of {planet}, which was lazy of the dream, as {name} was already there." },
		{ b : "rest", t : "a quiet room. {name} has nothing to add. {name} is asleep.", pers : "sleepy" },
		{ b : "rest", t : "rested for almost a whole minute. {name} is calling it a retreat.", pers : "eager" },
		{ b : "rest", t : "a nice room, {name} admits, with the air of someone admitting to a crime.", pers : "grumpy" },
		{ b : "rest", t : "a quiet room. {name} sat in the middle of it so as not to bother the edges.", pers : "shy" },
		{ b : "trap", t : "stepped on a thing that was clearly a trap, on the grounds that it looked like the only floor." },
		{ b : "trap", t : "a trap. {name} has learned from it. specifically, {name} has learned where it is." },
		{ b : "trap", t : "a dart came out of the wall. {name} caught it, which would have been impressive from the front." },
		{ b : "trap", t : "the floor gave way a little. {name} gave way a lot. everyone has recovered." },
		{ b : "trap", t : "a trap went off. {name} yelled a word that will not be recorded here, out of respect for the diary." },
		{ b : "trap", t : "{name} triggered a trap, then triggered it again to see if the first time was a fluke. it was not a fluke." },
		{ b : "trap", t : "a rock fell. {name} was under it briefly, then next to it. that is progress." },
		{ b : "trap", t : "there was a tripwire. {name} tripped. the wire did its job and {name} did the rest." },
		{ b : "trap", t : "{name} is fine. {name} has said \"i'm fine\" enough times now that it has become a chant.", hp : "low", w : 3 },
		{ b : "trap", t : "another trap. {name} is starting to take {planet} personally.", hp : "low", w : 3 },
		{ b : "trap", t : "{planet} again, and {name} knows where the traps are now. stepped on them in a new order.", need : "revisit", w : 3 },
		{ b : "trap", t : "that was the last one {name} had in them. heading back, at a walk that would like to be a run.", w : 6, routed : true },
		{ b : "fight_open", t : "{foe} blocks the way. {name} has explained that this is a public corridor. {foe} disagrees, physically." },
		{ b : "fight_open", t : "{foe}. {name} has never seen one before and would have been fine keeping it that way." },
		{ b : "fight_open", t : "{foe} stepped out of the dark. {name} stepped back into it. they have swapped, and neither is happy." },
		{ b : "fight_open", t : "{foe} made a noise. {name} made the same noise back, which turns out to mean \"fight\"." },
		{ b : "fight_open", t : "{foe}. {name} said \"nice {foe}\". it is not a nice {foe}." },
		{ b : "fight_open", t : "{foe} appeared. {name} checked behind for help. there was a wall. the wall is neutral." },
		{ b : "fight_open", t : "{foe} is bigger up close. most things are. {name} has decided to be brave from further away." },
		{ b : "fight_open", t : "{foe} and {name} regarded each other. {foe} regarded harder." },
		{ b : "fight_open", t : "{foe}. {name} has beaten worse. {name} cannot name any worse, but has beaten it.", pers : "smug" },
		{ b : "fight_open", t : "{foe} blocks the way. {name} tried \"excuse me\". {foe} is not the excusing sort.", pers : "shy" },
		{ b : "fight_open", t : "{foe} blocks the way. {name} checked it for pockets first. no pockets. now it is a fight.", pers : "greedy" },
		{ b : "fight_open", t : "{foe}. finally. {name} has been swinging at the air for practice and the air was getting bored.", pers : "eager" },
		{ b : "fight_open", t : "{name} has won three fights now and has begun referring to the arm as \"the arm\". {foe} has not been told.", need : "wins3", w : 3 },
		{ b : "fight_won", t : "{foe} has fallen. {name} would like it recorded that the foe started it, and that {name} finished it, eventually, from behind." },
		{ b : "fight_won", t : "{foe} is down. {name} stood over it for a bit, then apologised, then took the room." },
		{ b : "fight_won", t : "won. {name} is going to tell this story better than it happened, and that is the diary's official position too." },
		{ b : "fight_won", t : "{foe} gave up in the end. so did {name}, but slightly later, which is called winning." },
		{ b : "fight_won", t : "the way is clear. {name} has a new limp and a new story and considers this a fair trade." },
		{ b : "fight_won", t : "{foe} is beaten. {name} checked twice. {foe} stayed beaten both times." },
		{ b : "fight_won", t : "{name} hit {foe} until {foe} stopped, which is the whole of the technique." },
		{ b : "fight_won", t : "victory. {name} did a lap of the room. the room is small. it was a short lap." },
		{ b : "fight_lost", t : "{name} performed a tactical retreat at a speed that suggests the tactic was fear." },
		{ b : "fight_lost", t : "{foe} won. {name} left the room, then the corridor, then, on reflection, the planet." },
		{ b : "fight_lost", t : "{name} decided the fight was going badly and stopped attending it." },
		{ b : "fight_lost", t : "routed. {name} would like the record to show {foe} was enormous, and the record will show that, because {name} is holding the pen." },
		{ b : "fight_lost", t : "{name} ran. the running was excellent. the fight before it, less so." },
		{ b : "fight_lost", t : "{foe} chased {name} as far as the door and then lost interest. {name} has not lost interest and is still running." },
		{ b : "return", t : "heading home. {name} has counted the loot four times and got three different answers, all of them \"some\".", routed : false },
		{ b : "return", t : "leaving {planet}. {name} looked back once, for the diary. it was still there.", routed : false },
		{ b : "return", t : "home stretch. {name} is rehearsing the story and has already promoted the rooms to caves and the caves to depths.", routed : false },
		{ b : "return", t : "{name} left {planet} a little tidier than it was found, by taking things from it.", routed : false },
		{ b : "return", t : "the ship again. {name} sat in the same seat, which is now \"my seat\".", routed : false },
		{ b : "return", t : "on the way back {name} noticed a bruise and could not place it. it has been filed under \"adventure\".", routed : false },
		{ b : "return", t : "{planet} is getting smaller in the window. {name} is waving. this is a thing {name} does now.", routed : false },
		{ b : "return", t : "heading home with the haul. {name} keeps checking the bag is still a bag.", routed : false },
		{ b : "return", t : "heading home early. {name} is calling it a scouting trip and would like everyone else to as well.", w : 3, routed : true },
		{ b : "return", t : "the way back is shorter when you are running. {name} has tested this thoroughly.", w : 3, routed : true },
		{ b : "return", t : "leaving {planet} in a hurry. {name} would like to make clear that the planet started it.", w : 3, routed : true },
		{ b : "home", t : "home. {name} smells like {planet} and has decided that is a personality now.", routed : false },
		{ b : "home", t : "back. {name} told the story once, accurately, by accident. the next tellings have been corrected.", routed : false },
		{ b : "home", t : "home. the first thing {name} did was sit down. the second thing was also that.", routed : false },
		{ b : "home", t : "{name} is back and has been asked \"how was it\". the answer, \"big\", has been accepted.", routed : false },
		{ b : "home", t : "home. {name} has put the finds in a pile and is looking at the pile. it is a good pile.", routed : false },
		{ b : "home", t : "back from {planet}. {name} has one new scar and three new opinions about rocks.", routed : false },
		{ b : "home", t : "home. {name} slept for a long time and woke up still tired, which is how you know it was a real trip.", routed : false },
		{ b : "home", t : "landed home. {name} kissed the ground, then wiped the ground off, then wiped that off.", routed : false },
		{ b : "home", t : "home, limping. {name} has decided the limp is a souvenir.", w : 3, routed : true },
		{ b : "home", t : "back early. nobody asked. {name} told them anyway.", w : 3, routed : true },
		{ b : "home", t : "home. {name} is not talking about {planet}. {name} has said \"i'm not talking about it\" eleven times.", w : 3, routed : true },
		{ b : "sky", t : "the sky did nothing again today. {name} assumes this is a test and is passing it by also doing nothing." },
		{ b : "sky", t : "{name} looked up and said thanks, to be safe. nothing answered. that is usually what nothing does." },
		{ b : "sky", t : "{name} felt watched today, in a good way, like a plant on a windowsill." },
		{ b : "sky", t : "{name} asked the sky for a sign. a rock fell. {name} has decided that was not the sign, and is waiting for a nicer one." },
		{ b : "sky", t : "dear whoever is up there: the snacks are fine. no complaints. small complaint about the cold. fine." },
		{ b : "sky", t : "{name} thanked the sky for the good weather. the weather is not good. {name} is being polite in advance." },
		{ b : "travel", t : "{name} and {partner} walked in silence for an hour. {name} thinks it went well.", party : 2, bond : 1 },
		{ b : "rest", t : "{partner} said something. {name} said \"yes\". it was not a yes question. they have agreed to move on.", party : 2, bond : 1 },
		{ b : "trap", t : "{partner} tripped. {name} laughed, then tripped in solidarity, then just tripped.", party : 2, bond : 2 },
		{ b : "find", t : "{name} and {partner} have a system. {name} points at things and {partner} says \"no\". it is working.", party : 2, bond : 2 },
		{ b : "rest", t : "{name} and {partner} shared the last ration by both pretending not to be hungry until it went off.", party : 2, bond : 3 },
		{ b : "travel", t : "{partner} knew what {name} was going to say and said it first. {name} said it anyway. twice.", party : 2, bond : 3 },
		{ b : "fight_open", t : "{foe} blocks the way. {name} looked at {partner}. {partner} looked at {name}. {foe} looked at both, and won that part.", party : 2 },
		{ b : "fight_won", t : "{foe} is down. {name} and {partner} are each telling it as a solo victory. the diary is staying out of it.", party : 2 },
		{ b : "fight_lost", t : "{name} and {partner} ran in different directions, then the same direction, then home.", party : 2 },
		{ b : "rest", t : "a quiet room. {partner} snored. {name} snored back. an accord was reached.", party : 2 },
	];
	return _l;
}
